// 영어 기출 단어장 (파트 3)
(window.ENGLISH_VOCAB = window.ENGLISH_VOCAB || []).push(
  { w: "fire", p: "명", m: "불, 화재", f: ["fire"], lv: 1 },
  { w: "first", p: "형", m: "첫째의, 처음, 먼저", f: ["first"], lv: 1 },
  { w: "fish", p: "명", m: "물고기, 낚시하다", f: ["fish", "fishing"], lv: 1 },
  { w: "fitness", p: "명", m: "건강, 신체 단련", f: ["fitness"], lv: 2 },
  { w: "five", p: "명", m: "다섯, 5", f: ["five"], lv: 1 },
  { w: "fix", p: "동", m: "고치다, 수리하다", f: ["fix"], lv: 1 },
  { w: "flavor", p: "명", m: "맛, 풍미, 맛을 내다", f: ["flavor", "flavored"], lv: 2 },
  { w: "flexibility", p: "명", m: "유연성, 융통성", f: ["flexibility"], lv: 3 },
  { w: "fly", p: "동", m: "날다, 비행하다", f: ["flies"], lv: 1 },
  { w: "flight", p: "명", m: "비행, 항공편", f: ["flight"], lv: 2 },
  { w: "flood", p: "명", m: "홍수", f: ["flood"], lv: 2 },
  { w: "floor", p: "명", m: "바닥, 층", f: ["floor"], lv: 1 },
  { w: "flower", p: "명", m: "꽃", f: ["flower", "flowers"], lv: 1, u: true },
  { w: "flowering", p: "형", m: "꽃이 피는", f: ["flowering"], lv: 2 },
  { w: "focus", p: "동", m: "집중하다, 초점", f: ["focus", "focused", "focuses"], lv: 2 },
  { w: "fold", p: "동", m: "접다", f: ["folding"], lv: 2 },
  { w: "follow", p: "동", m: "따르다, 따라가다", f: ["follow"], lv: 1 },
  { w: "following", p: "형", m: "다음의, 아래의", f: ["following"], lv: 2 },
  { w: "food", p: "명", m: "음식, 식품", f: ["food", "foods"], lv: 1, u: true },
  { w: "forbid", p: "동", m: "금지하다", f: ["forbid"], lv: 3 },
  { w: "force", p: "동", m: "강요하다, 억지로 ~하게 하다", f: ["forced"], lv: 2 },
  { w: "forecast", p: "명", m: "예보, 예측", f: ["forecast"], lv: 2 },
  { w: "forecaster", p: "명", m: "기상 예보관, 예측자", f: ["forecasters"], lv: 3 },
  { w: "foreigner", p: "명", m: "외국인", f: ["foreigners"], lv: 2 },
  { w: "forest", p: "명", m: "숲", f: ["forest"], lv: 1 },
  { w: "forget", p: "동", m: "잊다", f: ["forget", "forgot", "forgotten"], lv: 1 },
  { w: "fork", p: "명", m: "포크", f: ["fork"], lv: 1 },
  { w: "form", p: "명", m: "형태, 양식, 형성하다", f: ["form", "formed", "forms"], lv: 2 },
  { w: "forth", p: "부", m: "앞으로 (back and forth 왔다 갔다)", f: ["forth"], lv: 2 },
  { w: "fortunately", p: "부", m: "다행히", f: ["fortunately"], lv: 2 },
  { w: "forward", p: "부", m: "앞으로", f: ["forward"], lv: 2 },
  { w: "fossil", p: "명", m: "화석 (fossil fuel 화석 연료)", f: ["fossil"], lv: 3 },
  { w: "find", p: "동", m: "찾다, 발견하다, 알게 되다", f: ["found"], lv: 1 },
  { w: "four", p: "명", m: "넷, 4", f: ["four"], lv: 1 },
  { w: "frame", p: "명", m: "틀, 액자", f: ["frame"], lv: 2 },
  { w: "free", p: "형", m: "무료의, 자유로운", f: ["free"], lv: 1 },
  { w: "freeze", p: "동", m: "얼다, 몹시 추운, 냉동된", f: ["freezing", "frozen"], lv: 2 },
  { w: "French", p: "형", m: "프랑스의, 프랑스어", f: ["french"], lv: 1 },
  { w: "frequent", p: "형", m: "잦은, 빈번한", f: ["frequent"], lv: 2 },
  { w: "frequently", p: "부", m: "자주, 빈번히", f: ["frequently"], lv: 2 },
  { w: "fresh", p: "형", m: "신선한, 새로운", f: ["fresh"], lv: 1 },
  { w: "freshly", p: "부", m: "갓, 새로", f: ["freshly"], lv: 2 },
  { w: "Friday", p: "명", m: "금요일", f: ["friday", "fridays"], lv: 1 },
  { w: "friend", p: "명", m: "친구", f: ["friend", "friends"], lv: 1 },
  { w: "friendly", p: "형", m: "친절한, 다정한, 친화적인", f: ["friendly"], lv: 1 },
  { w: "frightened", p: "형", m: "겁먹은, 무서워하는", f: ["frightened"], lv: 2 },
  { w: "front", p: "명", m: "앞, 정면", f: ["front"], lv: 1 },
  { w: "fruit", p: "명", m: "과일, 열매", f: ["fruit", "fruits"], lv: 1, u: true },
  { w: "frustrated", p: "형", m: "좌절한, 답답한", f: ["frustrated"], lv: 2 },
  { w: "fuel", p: "명", m: "연료", f: ["fuel", "fuels"], lv: 2 },
  { w: "full", p: "형", m: "가득 찬, 배부른", f: ["full"], lv: 1, u: true },
  { w: "fun", p: "명", m: "재미, 재미있는", f: ["fun"], lv: 1 },
  { w: "function", p: "명", m: "기능, 작동하다", f: ["function"], lv: 2 },
  { w: "fundraising", p: "명", m: "기금 모금", f: ["fundraising"], lv: 3 },
  { w: "fund", p: "명", m: "기금, 자금", f: ["funds"], lv: 2 },
  { w: "furniture", p: "명", m: "가구", f: ["furniture"], lv: 2 },
  { w: "furthermore", p: "부", m: "게다가, 더욱이", f: ["furthermore"], lv: 2 },
  { w: "future", p: "명", m: "미래", f: ["future"], lv: 1 },
  { w: "gain", p: "동", m: "얻다, (체중이) 늘다", f: ["gain", "gained"], lv: 2 },
  { w: "game", p: "명", m: "경기, 게임", f: ["game", "games"], lv: 1 },
  { w: "garage", p: "명", m: "차고", f: ["garage"], lv: 2 },
  { w: "garden", p: "명", m: "정원", f: ["garden"], lv: 1 },
  { w: "gas", p: "명", m: "가스, 기체", f: ["gas"], lv: 1 },
  { w: "gate", p: "명", m: "문, 출입구", f: ["gate"], lv: 1 },
  { w: "gather", p: "동", m: "모이다, 모으다, 모임", f: ["gathering"], lv: 2 },
  { w: "give", p: "동", m: "주다", f: ["give", "gave", "given", "gives", "giving"], lv: 1 },
  { w: "gently", p: "부", m: "부드럽게, 살살", f: ["gently"], lv: 2 },
  { w: "German", p: "형", m: "독일의, 독일어", f: ["german"], lv: 1 },
  { w: "gesture", p: "명", m: "몸짓, 제스처", f: ["gesture", "gestures"], lv: 2 },
  { w: "get", p: "동", m: "얻다, 받다, ~하게 되다", f: ["get", "gets", "getting", "got"], lv: 1 },
  { w: "gift", p: "명", m: "선물, 재능", f: ["gift"], lv: 1 },
  { w: "gifted", p: "형", m: "재능 있는", f: ["gifted"], lv: 2 },
  { w: "kimchi", p: "명", m: "김치", f: ["kimchi", "gimchi"], lv: 1 },
  { w: "girlfriend", p: "명", m: "여자 친구", f: ["girlfriend"], lv: 1 },
  { w: "glacier", p: "명", m: "빙하", f: ["glaciers"], lv: 3 },
  { w: "glass", p: "명", m: "유리, 유리잔, (복수) 안경", f: ["glass", "glasses"], lv: 1 },
  { w: "global", p: "형", m: "세계적인, 지구의", f: ["global"], lv: 2 },
  { w: "glove", p: "명", m: "장갑", f: ["gloves"], lv: 1 },
  { w: "go", p: "동", m: "가다", f: ["go", "goes", "going", "gone"], lv: 1 },
  { w: "goal", p: "명", m: "목표, 골", f: ["goal", "goals"], lv: 1, u: true },
  { w: "good", p: "형", m: "좋은, 잘하는", f: ["good"], lv: 1 },
  { w: "goods", p: "명", m: "상품, 물건", f: ["goods"], lv: 2 },
  { w: "gorgeous", p: "형", m: "아주 멋진, 아름다운", f: ["gorgeous"], lv: 3 },
  { w: "government", p: "명", m: "정부", f: ["government"], lv: 2 },
  { w: "grade", p: "명", m: "학년, 성적, 등급", f: ["grade"], lv: 1 },
  { w: "gradually", p: "부", m: "점차, 서서히", f: ["gradually"], lv: 2 },
  { w: "graduate", p: "동", m: "졸업하다, 졸업생", f: ["graduate"], lv: 2 },
  { w: "grand", p: "형", m: "웅장한, 큰", f: ["grand"], lv: 2 },
  { w: "grandfather", p: "명", m: "할아버지", f: ["grandfather"], lv: 1 },
  { w: "grandmother", p: "명", m: "할머니", f: ["grandmother"], lv: 1 },
  { w: "grasshopper", p: "명", m: "메뚜기, 베짱이", f: ["grasshopper"], lv: 3 },
  { w: "gravity", p: "명", m: "중력", f: ["gravity"], lv: 3 },
  { w: "gray", p: "형", m: "회색의, 회색", f: ["gray"], lv: 1 },
  { w: "great", p: "형", m: "훌륭한, 큰, 대단한", f: ["great", "greatest"], lv: 1 },
  { w: "greatly", p: "부", m: "크게, 대단히", f: ["greatly"], lv: 2 },
  { w: "Greek", p: "명", m: "그리스인, 그리스의", f: ["greek", "greeks"], lv: 2 },
  { w: "green", p: "형", m: "초록색의, 녹색", f: ["green"], lv: 1 },
  { w: "groceries", p: "명", m: "식료품, 장보기", f: ["groceries"], lv: 2 },
  { w: "ground", p: "명", m: "땅, 지면", f: ["ground"], lv: 1 },
  { w: "group", p: "명", m: "무리, 단체, 모둠", f: ["group", "groups"], lv: 1 },
  { w: "grow", p: "동", m: "자라다, 기르다", f: ["grow"], lv: 1 },
  { w: "guesthouse", p: "명", m: "게스트하우스, 민박", f: ["guesthouse"], lv: 2 },
  { w: "guest", p: "명", m: "손님, 투숙객", f: ["guests"], lv: 1 },
  { w: "guideline", p: "명", m: "지침, 가이드라인", f: ["guidelines"], lv: 2 },
  { w: "guitar", p: "명", m: "기타", f: ["guitar"], lv: 1 },
  { w: "gym", p: "명", m: "체육관, 헬스장", f: ["gym"], lv: 1 },
  { w: "habit", p: "명", m: "습관", f: ["habit", "habits"], lv: 2, u: true },
  { w: "hair", p: "명", m: "머리카락, 털", f: ["hair"], lv: 1 },
  { w: "haircut", p: "명", m: "이발, 머리 자르기", f: ["haircut"], lv: 1 },
  { w: "hairstyle", p: "명", m: "머리 모양", f: ["hairstyles"], lv: 1 },
  { w: "half", p: "명", m: "절반, 반", f: ["half"], lv: 1 },
  { w: "hall", p: "명", m: "회관, 강당, 복도", f: ["hall"], lv: 1 },
  { w: "hammer", p: "명", m: "망치", f: ["hammer"], lv: 2 },
  { w: "hand", p: "명", m: "손, 건네주다", f: ["hand", "hands"], lv: 1 },
  { w: "handball", p: "명", m: "핸드볼", f: ["handball"], lv: 2 },
  { w: "handle", p: "동", m: "다루다, 처리하다, 손잡이", f: ["handled"], lv: 2 },
  { w: "handmade", p: "형", m: "손으로 만든, 수제의", f: ["handmade"], lv: 2 },
  { w: "hang", p: "동", m: "걸다, 매달다", f: ["hang"], lv: 2 },
  { w: "happen", p: "동", m: "일어나다, 발생하다", f: ["happen", "happened", "happens"], lv: 1 },
  { w: "happy", p: "형", m: "행복한, 기쁜", f: ["happy", "happier", "happiest"], lv: 1, u: true },
  { w: "happiness", p: "명", m: "행복", f: ["happiness"], lv: 2 },
  { w: "hard", p: "형", m: "어려운, 단단한, 열심히", f: ["hard"], lv: 1 },
  { w: "harm", p: "동", m: "해치다, 해, 손상", f: ["harm", "harming"], lv: 2 },
  { w: "harmful", p: "형", m: "해로운", f: ["harmful"], lv: 2 },
  { w: "harmony", p: "명", m: "조화, 화합", f: ["harmony"], lv: 2 },
  { w: "harsh", p: "형", m: "혹독한, 가혹한", f: ["harsh"], lv: 3 },
  { w: "hat", p: "명", m: "모자", f: ["hat"], lv: 1 },
  { w: "headache", p: "명", m: "두통", f: ["headache"], lv: 1 },
  { w: "headlight", p: "명", m: "전조등", f: ["headlights"], lv: 2 },
  { w: "headphones", p: "명", m: "헤드폰", f: ["headphones"], lv: 1 },
  { w: "head", p: "명", m: "머리, 향하다", f: ["heads"], lv: 1 },
  { w: "heal", p: "동", m: "치유하다, 낫게 하다", f: ["heal"], lv: 2 },
  { w: "health", p: "명", m: "건강", f: ["health"], lv: 1 },
  { w: "healthy", p: "형", m: "건강한, 건강에 좋은", f: ["healthy"], lv: 1 },
  { w: "hear", p: "동", m: "듣다, 들리다", f: ["hear", "heard", "hearing"], lv: 1 },
  { w: "heart", p: "명", m: "마음, 심장", f: ["heart", "hearts"], lv: 1 },
  { w: "good-hearted", p: "형", m: "마음씨 좋은, 선량한", f: ["hearted"], lv: 3 },
  { w: "heat", p: "명", m: "열, 더위, 난방", f: ["heat", "heating"], lv: 2 },
  { w: "heavily", p: "부", m: "심하게, 많이", f: ["heavily"], lv: 2 },
  { w: "heavy", p: "형", m: "무거운, 심한", f: ["heavy"], lv: 1 },
  { w: "hold", p: "동", m: "열다(개최하다), 잡다", f: ["hold", "held", "holding", "holds"], lv: 1 },
  { w: "hello", p: "감", m: "안녕하세요, 여보세요", f: ["hello"], lv: 1 },
  { w: "help", p: "동", m: "돕다, 도움", f: ["help", "helped", "helps"], lv: 1 },
  { w: "helpful", p: "형", m: "도움이 되는, 유용한", f: ["helpful"], lv: 1 },
  { w: "hey", p: "감", m: "이봐, 야", f: ["hey"], lv: 1 },
  { w: "hi", p: "감", m: "안녕", f: ["hi"], lv: 1 },
  { w: "high", p: "형", m: "높은", f: ["high", "higher"], lv: 1 },
  { w: "hike", p: "동", m: "도보 여행하다, 등산하다", f: ["hiking"], lv: 2 },
  { w: "hill", p: "명", m: "언덕", f: ["hills"], lv: 1 },
  { w: "historical", p: "형", m: "역사적인, 역사의", f: ["historical"], lv: 2 },
  { w: "history", p: "명", m: "역사", f: ["history"], lv: 1 },
  { w: "hit", p: "동", m: "치다, 때리다", f: ["hit"], lv: 1 },
  { w: "hmm", p: "감", m: "음 (망설임)", f: ["hmm"], lv: 1 },
  { w: "home", p: "명", m: "집, 가정, 집에", f: ["home"], lv: 1 },
  { w: "homepage", p: "명", m: "홈페이지", f: ["homepage"], lv: 1 },
  { w: "homework", p: "명", m: "숙제", f: ["homework"], lv: 1 },
  { w: "honest", p: "형", m: "정직한", f: ["honest"], lv: 1 },
  { w: "honesty", p: "명", m: "정직", f: ["honesty"], lv: 2 },
  { w: "honey", p: "명", m: "꿀", f: ["honey"], lv: 1 },
  { w: "hope", p: "동", m: "바라다, 희망", f: ["hope"], lv: 1 },
  { w: "hormone", p: "명", m: "호르몬", f: ["hormones"], lv: 3 },
  { w: "horror", p: "명", m: "공포", f: ["horror"], lv: 2 },
  { w: "horse", p: "명", m: "말", f: ["horse"], lv: 1 },
  { w: "hospital", p: "명", m: "병원", f: ["hospital"], lv: 1 },
  { w: "hot", p: "형", m: "더운, 뜨거운, 매운", f: ["hot"], lv: 1 },
  { w: "hotel", p: "명", m: "호텔", f: ["hotel"], lv: 1 },
  { w: "hour", p: "명", m: "시간, 1시간", f: ["hour", "hours"], lv: 1 },
  { w: "house", p: "명", m: "집", f: ["house", "houses"], lv: 1 },
  { w: "household", p: "명", m: "가구, 가정", f: ["household"], lv: 3 },
  { w: "housewarming", p: "명", m: "집들이", f: ["housewarming"], lv: 3 },
  { w: "however", p: "부", m: "그러나, 하지만", f: ["however"], lv: 2 },
  { w: "hug", p: "동", m: "껴안다, 포옹", f: ["hug"], lv: 1 },
  { w: "huge", p: "형", m: "거대한, 엄청난", f: ["huge"], lv: 1 },
  { w: "human", p: "명", m: "인간, 인간의", f: ["human", "humans"], lv: 1 },
  { w: "hundred", p: "명", m: "백, 100 (hundreds of 수백의)", f: ["hundreds"], lv: 1 },
  { w: "hungry", p: "형", m: "배고픈", f: ["hungry"], lv: 1 },
  { w: "hurry", p: "동", m: "서두르다", f: ["hurry"], lv: 1 },
  { w: "hurt", p: "동", m: "아프다, 다치게 하다", f: ["hurt", "hurts"], lv: 1 },
  { w: "ice", p: "명", m: "얼음", f: ["ice"], lv: 1 },
  { w: "idea", p: "명", m: "생각, 아이디어", f: ["idea", "ideas"], lv: 1 },
  { w: "ignore", p: "동", m: "무시하다", f: ["ignore", "ignoring"], lv: 2 },
  { w: "illness", p: "명", m: "병, 질환", f: ["illnesses"], lv: 2 },
  { w: "imagination", p: "명", m: "상상력", f: ["imagination"], lv: 2 },
  { w: "imagine", p: "동", m: "상상하다", f: ["imagine"], lv: 2 },
  { w: "impact", p: "명", m: "영향, 충격", f: ["impact"], lv: 2 },
  { w: "impolite", p: "형", m: "무례한, 버릇없는", f: ["impolite"], lv: 2 },
  { w: "important", p: "형", m: "중요한", f: ["important"], lv: 1 },
  { w: "importantly", p: "부", m: "중요하게 (more importantly 더 중요한 것은)", f: ["importantly"], lv: 2 },
  { w: "impossible", p: "형", m: "불가능한", f: ["impossible"], lv: 2 },
  { w: "improve", p: "동", m: "향상시키다, 개선하다", f: ["improve", "improves"], lv: 2 },
  { w: "include", p: "동", m: "포함하다", f: ["include", "included", "including"], lv: 2 },
  { w: "inconvenience", p: "명", m: "불편", f: ["inconvenience"], lv: 3 },
  { w: "incorrect", p: "형", m: "틀린, 부정확한", f: ["incorrect"], lv: 2 },
  { w: "increase", p: "동", m: "증가하다, 늘리다, 증가", f: ["increase", "increased", "increases", "increasing"], lv: 2 },
  { w: "indeed", p: "부", m: "실제로, 정말로", f: ["indeed"], lv: 2 },
  { w: "independent", p: "형", m: "독립적인, 자립한", f: ["independent"], lv: 2 },
  { w: "indicate", p: "동", m: "나타내다, 가리키다", f: ["indicates"], lv: 3 },
  { w: "individual", p: "명", m: "개인, 개인의", f: ["individuals"], lv: 2 },
  { w: "indoors", p: "부", m: "실내에서", f: ["indoors"], lv: 2 },
  { w: "influence", p: "동", m: "영향을 주다, 영향", f: ["influences"], lv: 2 },
  { w: "inform", p: "동", m: "알리다, 통지하다", f: ["inform", "informed"], lv: 2 },
  { w: "information", p: "명", m: "정보", f: ["information"], lv: 1 },
  { w: "injure", p: "동", m: "다치게 하다, 부상당한", f: ["injured"], lv: 2 },
  { w: "injury", p: "명", m: "부상", f: ["injuries"], lv: 2 },
  { w: "ink", p: "명", m: "잉크", f: ["ink"], lv: 1 },
  { w: "inner", p: "형", m: "내부의, 내면의", f: ["inner"], lv: 2 },
  { w: "innovative", p: "형", m: "혁신적인", f: ["innovative"], lv: 3 },
  { w: "insect", p: "명", m: "곤충", f: ["insects"], lv: 1 },
  { w: "inside", p: "부", m: "안에, 내부", f: ["inside"], lv: 1 },
  { w: "insist", p: "동", m: "주장하다, 고집하다", f: ["insist"], lv: 2 },
  { w: "inspire", p: "동", m: "영감을 주다, 고무하다", f: ["inspired"], lv: 3 },
  { w: "instance", p: "명", m: "예, 사례 (for instance 예를 들어)", f: ["instance"], lv: 2 },
  { w: "instead", p: "부", m: "대신에", f: ["instead"], lv: 2 },
  { w: "instruction", p: "명", m: "설명, 지시", f: ["instructions"], lv: 2 },
  { w: "instrument", p: "명", m: "악기, 도구", f: ["instrument", "instruments"], lv: 2 },
  { w: "intelligence", p: "명", m: "지능 (artificial intelligence 인공지능)", f: ["intelligence"], lv: 3 },
  { w: "intend", p: "동", m: "의도하다, ~할 작정이다", f: ["intend"], lv: 3 },
  { w: "intense", p: "형", m: "강렬한, 극심한", f: ["intense"], lv: 3 },
  { w: "interested", p: "형", m: "관심 있는", f: ["interested"], lv: 1 },
  { w: "interesting", p: "형", m: "흥미로운, 재미있는", f: ["interesting"], lv: 1 },
  { w: "international", p: "형", m: "국제적인", f: ["international"], lv: 2 },
  { w: "internationally", p: "부", m: "국제적으로", f: ["internationally"], lv: 3 },
  { w: "Internet", p: "명", m: "인터넷", f: ["internet"], lv: 1 },
  { w: "interpret", p: "동", m: "해석하다, 이해하다", f: ["interpreted"], lv: 3 },
  { w: "introduction", p: "명", m: "소개, 도입", f: ["introduction"], lv: 2 },
  { w: "invent", p: "동", m: "발명하다", f: ["invent", "invented", "inventing"], lv: 2 },
  { w: "invention", p: "명", m: "발명, 발명품", f: ["invention", "inventions"], lv: 2 },
  { w: "inventor", p: "명", m: "발명가", f: ["inventor"], lv: 2 },
  { w: "invite", p: "동", m: "초대하다", f: ["invited"], lv: 1 },
  { w: "island", p: "명", m: "섬", f: ["island"], lv: 1 },
  { w: "issue", p: "명", m: "문제, 쟁점", f: ["issues"], lv: 2 },
  { w: "Italian", p: "형", m: "이탈리아의, 이탈리아어", f: ["italian"], lv: 1 },
  { w: "item", p: "명", m: "물품, 항목", f: ["item", "items"], lv: 2 },
  { w: "jacket", p: "명", m: "재킷, 웃옷", f: ["jacket"], lv: 1 },
  { w: "jam", p: "명", m: "잼", f: ["jam"], lv: 1 },
  { w: "jeans", p: "명", m: "청바지", f: ["jeans"], lv: 1 },
  { w: "job", p: "명", m: "일, 직업", f: ["job", "jobs"], lv: 1 },
  { w: "join", p: "동", m: "참여하다, 가입하다", f: ["join"], lv: 1 },
  { w: "journey", p: "명", m: "여행, 여정", f: ["journey"], lv: 2 },
  { w: "joy", p: "명", m: "기쁨", f: ["joy"], lv: 1 },
  { w: "judge", p: "동", m: "판단하다, 심판, 판사", f: ["judge"], lv: 2 },
  { w: "juice", p: "명", m: "주스, 즙", f: ["juices"], lv: 1 },
  { w: "July", p: "명", m: "7월", f: ["july"], lv: 1 },
  { w: "jump", p: "동", m: "뛰다, 점프하다", f: ["jump", "jumping"], lv: 1 },
  { w: "jumper", p: "명", m: "점퍼 (jumper cables 충전용 케이블)", f: ["jumper"], lv: 2 },
  { w: "June", p: "명", m: "6월", f: ["june"], lv: 1 },
  { w: "jungle", p: "명", m: "정글, 밀림", f: ["jungle"], lv: 2 },
  { w: "keen", p: "형", m: "날카로운, 예리한, 열망하는", f: ["keen"], lv: 3 },
  { w: "keep", p: "동", m: "유지하다, 계속 ~하다, 지키다", f: ["keep", "keeping", "keeps", "kept"], lv: 1 },
  { w: "key", p: "명", m: "열쇠, 핵심, 중요한", f: ["key"], lv: 1 },
  { w: "kick", p: "동", m: "차다", f: ["kick"], lv: 1 },
  { w: "kid", p: "명", m: "아이", f: ["kids"], lv: 1 },
  { w: "kind", p: "명", m: "종류, 친절한", f: ["kind", "kinds"], lv: 1 },
  { w: "kindness", p: "명", m: "친절", f: ["kindness"], lv: 2 },
  { w: "king", p: "명", m: "왕", f: ["kings"], lv: 1 },
  { w: "kitchen", p: "명", m: "부엌", f: ["kitchen"], lv: 1 },
  { w: "know", p: "동", m: "알다", f: ["know", "knew", "known", "knows"], lv: 1 },
  { w: "knife", p: "명", m: "칼", f: ["knife"], lv: 1 },
  { w: "knowledge", p: "명", m: "지식", f: ["knowledge"], lv: 2, u: true },
  { w: "koala", p: "명", m: "코알라", f: ["koalas"], lv: 1 },
  { w: "Korean", p: "형", m: "한국의, 한국인, 한국어", f: ["korean", "koreans"], lv: 1 },
  { w: "lack", p: "명", m: "부족, 결핍, 부족하다", f: ["lack"], lv: 2 },
  { w: "lake", p: "명", m: "호수", f: ["lake"], lv: 1 },
  { w: "landfill", p: "명", m: "쓰레기 매립지", f: ["landfills"], lv: 3 },
  { w: "language", p: "명", m: "언어", f: ["language"], lv: 1 },
  { w: "large", p: "형", m: "큰, 많은", f: ["large"], lv: 1 },
  { w: "last", p: "형", m: "지난, 마지막의, 지속되다", f: ["last", "lasts"], lv: 1 },
  { w: "lastly", p: "부", m: "마지막으로", f: ["lastly"], lv: 2 },
  { w: "late", p: "형", m: "늦은, 늦게", f: ["late", "later"], lv: 1 },
  { w: "lately", p: "부", m: "최근에", f: ["lately"], lv: 2 },
  { w: "laugh", p: "동", m: "웃다", f: ["laugh", "laughing"], lv: 1 },
  { w: "laughter", p: "명", m: "웃음", f: ["laughter"], lv: 2 },
  { w: "lavender", p: "명", m: "라벤더", f: ["lavender"], lv: 2 },
  { w: "layer", p: "명", m: "층, 겹", f: ["layer"], lv: 2 },
  { w: "lead", p: "동", m: "이끌다, (결과로) 이어지다", f: ["lead", "leads"], lv: 2 },
  { w: "lean", p: "동", m: "기대다, 숙이다", f: ["leaning"], lv: 2 },
  { w: "leap", p: "동", m: "뛰다, 도약하다", f: ["leap"], lv: 3 },
  { w: "learn", p: "동", m: "배우다", f: ["learn", "learning"], lv: 1 },
  { w: "leave", p: "동", m: "떠나다, 남기다, 두고 오다", f: ["leave", "leaves", "left"], lv: 1 },
  { w: "hang out with", p: "숙어", m: "~와 어울려 놀다", f: ["hang out with"], lv: 2, ph: true, u: true },
  { w: "get rid of", p: "숙어", m: "~을 없애다, 제거하다", f: ["get rid of"], lv: 2, ph: true, u: true },
  { w: "instead of", p: "숙어", m: "~ 대신에", f: ["instead of"], lv: 2, ph: true, u: true },
  { w: "in fact", p: "숙어", m: "사실은, 실제로", f: ["in fact"], lv: 2, ph: true, u: true },
  { w: "get along with", p: "숙어", m: "~와 잘 지내다", f: ["get along with"], lv: 2, ph: true, u: true },
  { w: "give up", p: "숙어", m: "포기하다", f: ["give up"], lv: 1, ph: true, u: true },
  { w: "for example", p: "숙어", m: "예를 들어", f: ["for example"], lv: 1, ph: true, u: true },
  { w: "keep in mind", p: "숙어", m: "명심하다, 기억해 두다", f: ["keep in mind"], lv: 2, ph: true, u: true },
  { w: "It's never too late to learn", p: "속담", m: "배움에 늦은 때란 없다", f: ["it's never too late to learn"], lv: 2, ph: true, u: true },
  { w: "Honesty is the best policy", p: "속담", m: "정직이 최선의 방책이다", f: ["honesty is the best policy"], lv: 2, ph: true, u: true }
);
