// 영어 기출 단어장 (파트 6)
(window.ENGLISH_VOCAB = window.ENGLISH_VOCAB || []).push(
  { w: "spider", p: "명", m: "거미", f: ["spider"], lv: 1 },
  { w: "spine", p: "명", m: "척추, 등뼈", f: ["spine"], lv: 3 },
  { w: "sport", p: "명", m: "운동, 스포츠", f: ["sport", "sports"], lv: 1 },
  { w: "spot", p: "명", m: "반점, 얼룩, 장소", f: ["spots"], lv: 2 },
  { w: "spread", p: "명", m: "확산, 퍼지다", f: ["spread", "spreading"], lv: 2 },
  { w: "spring", p: "명", m: "봄, 샘", f: ["spring"], lv: 1, u: true },
  { w: "stadium", p: "명", m: "경기장", f: ["stadium"], lv: 2 },
  { w: "stage", p: "명", m: "무대, 단계", f: ["stage"], lv: 2 },
  { w: "stair", p: "명", m: "계단", f: ["stairs"], lv: 1 },
  { w: "stand", p: "동", m: "서 있다, 서다, 참다", f: ["stand", "standing"], lv: 1 },
  { w: "starfish", p: "명", m: "불가사리", f: ["starfish"], lv: 2 },
  { w: "star", p: "명", m: "별, 스타", f: ["stars"], lv: 1 },
  { w: "start", p: "동", m: "시작하다, 출발하다", f: ["start", "started", "starts"], lv: 1 },
  { w: "state", p: "명", m: "주(州), 상태, 국가", f: ["state"], lv: 2 },
  { w: "station", p: "명", m: "역, 정거장", f: ["station"], lv: 1 },
  { w: "stay", p: "동", m: "머무르다, 유지하다", f: ["stay", "stayed", "staying", "stays"], lv: 1 },
  { w: "steady", p: "형", m: "꾸준한, 한결같은", f: ["steady"], lv: 2 },
  { w: "steak", p: "명", m: "스테이크", f: ["steak"], lv: 1 },
  { w: "step", p: "명", m: "단계, 걸음", f: ["step", "steps"], lv: 1 },
  { w: "stick", p: "명", m: "막대기, 붙이다", f: ["stick"], lv: 2 },
  { w: "still", p: "부", m: "여전히, 아직", f: ["still"], lv: 1 },
  { w: "steal", p: "동", m: "훔치다", f: ["stolen"], lv: 2 },
  { w: "stone", p: "명", m: "돌", f: ["stone"], lv: 1 },
  { w: "stop", p: "동", m: "멈추다, 그만두다", f: ["stop", "stopped", "stopping"], lv: 1 },
  { w: "store", p: "명", m: "가게, 저장하다", f: ["store", "stores"], lv: 1 },
  { w: "story", p: "명", m: "이야기", f: ["stories", "story"], lv: 1 },
  { w: "storm", p: "명", m: "폭풍", f: ["storm", "storms"], lv: 2 },
  { w: "straight", p: "형", m: "곧은, 똑바로", f: ["straight"], lv: 2 },
  { w: "strange", p: "형", m: "이상한, 낯선", f: ["strange"], lv: 1 },
  { w: "strategically", p: "부", m: "전략적으로", f: ["strategically"], lv: 3 },
  { w: "strategy", p: "명", m: "전략", f: ["strategy"], lv: 2 },
  { w: "strawberry", p: "명", m: "딸기", f: ["strawberry"], lv: 1 },
  { w: "street", p: "명", m: "거리, 길", f: ["street", "streets"], lv: 1 },
  { w: "stress", p: "명", m: "스트레스, 강조", f: ["stress"], lv: 2 },
  { w: "stretch", p: "동", m: "스트레칭하다, 늘이다", f: ["stretch"], lv: 2 },
  { w: "string", p: "명", m: "(악기의) 줄, 끈", f: ["strings"], lv: 2 },
  { w: "strong", p: "형", m: "강한, 튼튼한", f: ["strong"], lv: 1 },
  { w: "structure", p: "명", m: "구조물, 구조", f: ["structures"], lv: 2 },
  { w: "struggle", p: "명", m: "어려움, 투쟁, 애쓰다", f: ["struggles"], lv: 2 },
  { w: "student", p: "명", m: "학생", f: ["student", "students"], lv: 1 },
  { w: "study", p: "동", m: "공부하다, 연구", f: ["studied", "studies", "study", "studying"], lv: 1 },
  { w: "stuff", p: "명", m: "물건, 것", f: ["stuff"], lv: 2 },
  { w: "subject", p: "명", m: "과목, 주제", f: ["subject"], lv: 2 },
  { w: "submit", p: "동", m: "제출하다", f: ["submit"], lv: 2 },
  { w: "subway", p: "명", m: "지하철", f: ["subway"], lv: 1 },
  { w: "success", p: "명", m: "성공", f: ["success"], lv: 2 },
  { w: "successful", p: "형", m: "성공적인, 성공한", f: ["successful"], lv: 2 },
  { w: "suffer", p: "동", m: "고통받다, 겪다", f: ["suffer", "suffering"], lv: 2 },
  { w: "suggestion", p: "명", m: "제안", f: ["suggestions"], lv: 2 },
  { w: "suit", p: "명", m: "옷, 정장, 어울리다", f: ["suit", "suits"], lv: 2 },
  { w: "summary", p: "명", m: "요약", f: ["summaries", "summary"], lv: 2 },
  { w: "summer", p: "명", m: "여름", f: ["summer"], lv: 1 },
  { w: "sun", p: "명", m: "해, 태양", f: ["sun"], lv: 1 },
  { w: "sunburn", p: "명", m: "햇볕 화상", f: ["sunburn"], lv: 3 },
  { w: "Sunday", p: "명", m: "일요일", f: ["sunday", "sundays"], lv: 1 },
  { w: "sunflower", p: "명", m: "해바라기", f: ["sunflower"], lv: 2 },
  { w: "sunlight", p: "명", m: "햇빛", f: ["sunlight"], lv: 1 },
  { w: "sunscreen", p: "명", m: "자외선 차단제", f: ["sunscreen"], lv: 2 },
  { w: "superfood", p: "명", m: "슈퍼푸드(영양 많은 식품)", f: ["superfoods"], lv: 3 },
  { w: "supermarket", p: "명", m: "슈퍼마켓", f: ["supermarket"], lv: 1 },
  { w: "support", p: "동", m: "지지하다, 돕다, 지원", f: ["support"], lv: 2 },
  { w: "suppose", p: "동", m: "(be supposed to) ~하기로 되어 있다", f: ["supposed"], lv: 2 },
  { w: "sure", p: "형", m: "확실한, 물론", f: ["sure"], lv: 1 },
  { w: "surface", p: "명", m: "표면, 지표", f: ["surface"], lv: 2 },
  { w: "surprised", p: "형", m: "놀란", f: ["surprised"], lv: 1 },
  { w: "surround", p: "동", m: "둘러싸다", f: ["surrounded"], lv: 2 },
  { w: "survey", p: "명", m: "설문 조사", f: ["survey"], lv: 2 },
  { w: "survive", p: "동", m: "살아남다, 생존하다", f: ["survive"], lv: 2 },
  { w: "sweet", p: "형", m: "달콤한, 단", f: ["sweet"], lv: 1, u: true },
  { w: "swim", p: "동", m: "수영하다", f: ["swim", "swimming"], lv: 1 },
  { w: "switch", p: "동", m: "(switch off) 끄다, 바꾸다", f: ["switch"], lv: 2 },
  { w: "symbol", p: "명", m: "상징, 기호", f: ["symbol"], lv: 2 },
  { w: "system", p: "명", m: "체계, 시스템", f: ["system", "systems"], lv: 2 },
  { w: "table", p: "명", m: "탁자, 식탁, 표", f: ["table"], lv: 1 },
  { w: "taekwondo", p: "명", m: "태권도", f: ["taekwondo"], lv: 1 },
  { w: "take", p: "동", m: "가지고 가다, 타다, 걸리다", f: ["take", "taken", "takes", "taking", "took"], lv: 1 },
  { w: "talk", p: "동", m: "이야기하다, 말하다", f: ["talk", "talking"], lv: 1 },
  { w: "tall", p: "형", m: "키가 큰, 높은", f: ["tall", "taller"], lv: 1 },
  { w: "tank", p: "명", m: "(산소) 탱크, 통", f: ["tanks"], lv: 2 },
  { w: "task", p: "명", m: "일, 과제", f: ["tasks"], lv: 2 },
  { w: "taste", p: "동", m: "맛보다, 맛, 취향", f: ["taste", "tastes", "tasting"], lv: 1 },
  { w: "tea", p: "명", m: "차", f: ["tea"], lv: 1 },
  { w: "teach", p: "동", m: "가르치다", f: ["teach", "teaching"], lv: 1 },
  { w: "teacher", p: "명", m: "선생님, 교사", f: ["teacher", "teachers"], lv: 1 },
  { w: "team", p: "명", m: "팀, 조", f: ["team", "teams"], lv: 1 },
  { w: "teamwork", p: "명", m: "협동, 팀워크", f: ["teamwork"], lv: 2 },
  { w: "technical", p: "형", m: "기술적인", f: ["technical"], lv: 2 },
  { w: "technique", p: "명", m: "기법, 기술", f: ["techniques"], lv: 2 },
  { w: "technology", p: "명", m: "기술, 과학 기술", f: ["technology"], lv: 2 },
  { w: "teenager", p: "명", m: "십 대, 청소년", f: ["teenagers"], lv: 2 },
  { w: "television", p: "명", m: "텔레비전", f: ["television"], lv: 1 },
  { w: "TV", p: "명", m: "텔레비전", f: ["tv"], lv: 1 },
  { w: "tell", p: "동", m: "말하다, 알려 주다", f: ["tell", "told"], lv: 1 },
  { w: "temperature", p: "명", m: "온도, 기온, 체온", f: ["temperature", "temperatures"], lv: 2 },
  { w: "ten", p: "명", m: "10, 열", f: ["ten"], lv: 1 },
  { w: "tend", p: "동", m: "(tend to) ~하는 경향이 있다", f: ["tend"], lv: 2 },
  { w: "tennis", p: "명", m: "테니스", f: ["tennis"], lv: 1 },
  { w: "terrible", p: "형", m: "끔찍한, 심한", f: ["terrible"], lv: 2 },
  { w: "test", p: "명", m: "시험, 검사", f: ["test"], lv: 1 },
  { w: "thank", p: "동", m: "감사하다, 고마워하다", f: ["thank", "thanks"], lv: 1 },
  { w: "theater", p: "명", m: "극장", f: ["theater"], lv: 2 },
  { w: "therefore", p: "부", m: "그러므로, 따라서", f: ["therefore"], lv: 2 },
  { w: "thick", p: "형", m: "두꺼운, 굵은", f: ["thick"], lv: 2 },
  { w: "thin", p: "형", m: "얇은, 마른", f: ["thin"], lv: 1 },
  { w: "thing", p: "명", m: "것, 물건, 일", f: ["thing", "things"], lv: 1 },
  { w: "think", p: "동", m: "생각하다", f: ["think", "thinking", "thought"], lv: 1 },
  { w: "third", p: "형", m: "세 번째, 셋째로", f: ["third"], lv: 1 },
  { w: "though", p: "접", m: "~이지만, 그래도", f: ["though"], lv: 2 },
  { w: "thoughtful", p: "형", m: "사려 깊은, 배려하는", f: ["thoughtful"], lv: 2 },
  { w: "thousand", p: "명", m: "천(1,000)", f: ["thousand", "thousands"], lv: 1 },
  { w: "threaten", p: "동", m: "위협하다", f: ["threatening"], lv: 3 },
  { w: "three", p: "명", m: "3, 셋", f: ["three"], lv: 1 },
  { w: "throughout", p: "전", m: "~동안 내내, 도처에", f: ["throughout"], lv: 2 },
  { w: "throw", p: "동", m: "던지다, 버리다", f: ["throw"], lv: 1 },
  { w: "Thursday", p: "명", m: "목요일", f: ["thursday", "thursdays"], lv: 1 },
  { w: "thus", p: "부", m: "그러므로, 따라서", f: ["thus"], lv: 2 },
  { w: "ticket", p: "명", m: "표, 입장권", f: ["ticket", "tickets"], lv: 1 },
  { w: "tight", p: "형", m: "꽉 끼는, 단단한", f: ["tight"], lv: 2 },
  { w: "time", p: "명", m: "시간, 때, ~번", f: ["time", "times"], lv: 1 },
  { w: "tiny", p: "형", m: "아주 작은", f: ["tiny"], lv: 2 },
  { w: "tip", p: "명", m: "조언, 요령", f: ["tips"], lv: 2 },
  { w: "tired", p: "형", m: "피곤한, 지친", f: ["tired"], lv: 1 },
  { w: "today", p: "부", m: "오늘", f: ["today"], lv: 1 },
  { w: "together", p: "부", m: "함께, 같이", f: ["together"], lv: 1 },
  { w: "tomorrow", p: "부", m: "내일", f: ["tomorrow"], lv: 1 },
  { w: "tool", p: "명", m: "도구", f: ["tool", "tools"], lv: 1 },
  { w: "toothpaste", p: "명", m: "치약", f: ["toothpaste"], lv: 2 },
  { w: "top", p: "명", m: "꼭대기, 위, 최고의", f: ["top"], lv: 1 },
  { w: "topic", p: "명", m: "주제, 화제", f: ["topic"], lv: 2 },
  { w: "total", p: "형", m: "전체의, 합계", f: ["total"], lv: 2 },
  { w: "totally", p: "부", m: "완전히, 전적으로", f: ["totally"], lv: 2 },
  { w: "touch", p: "동", m: "만지다, 접촉", f: ["touch"], lv: 1 },
  { w: "tour", p: "명", m: "여행, 관광", f: ["tour"], lv: 1 },
  { w: "tourism", p: "명", m: "관광업, 관광", f: ["tourism"], lv: 2 },
  { w: "towards", p: "전", m: "~쪽으로, ~을 향하여", f: ["towards"], lv: 2 },
  { w: "tower", p: "명", m: "탑", f: ["tower"], lv: 1 },
  { w: "town", p: "명", m: "마을, 읍", f: ["town"], lv: 1 },
  { w: "toxic", p: "형", m: "독성의, 유독한", f: ["toxic"], lv: 3 },
  { w: "toy", p: "명", m: "장난감", f: ["toys"], lv: 1 },
  { w: "traditional", p: "형", m: "전통적인", f: ["traditional"], lv: 2 },
  { w: "traffic", p: "명", m: "교통, 교통량", f: ["traffic"], lv: 2 },
  { w: "train", p: "명", m: "기차, 훈련하다", f: ["train", "trained"], lv: 1 },
  { w: "training", p: "명", m: "훈련, 교육", f: ["training"], lv: 2 },
  { w: "transfer", p: "동", m: "환승하다, 옮기다", f: ["transfer"], lv: 2 },
  { w: "transform", p: "동", m: "변형시키다, 바꾸다", f: ["transform", "transformed"], lv: 3 },
  { w: "transportation", p: "명", m: "교통수단, 운송", f: ["transportation"], lv: 2, u: true },
  { w: "trash", p: "명", m: "쓰레기", f: ["trash"], lv: 1 },
  { w: "travel", p: "동", m: "여행하다, 이동하다", f: ["travel", "traveling", "travelling"], lv: 1 },
  { w: "treat", p: "동", m: "대하다, 치료하다", f: ["treated"], lv: 2 },
  { w: "tree", p: "명", m: "나무", f: ["tree", "trees"], lv: 1 },
  { w: "triangle", p: "명", m: "삼각형", f: ["triangle"], lv: 2 },
  { w: "trick", p: "동", m: "속이다, 속임수", f: ["trick"], lv: 2 },
  { w: "trip", p: "명", m: "여행", f: ["trip"], lv: 1 },
  { w: "trouble", p: "명", m: "문제, 어려움, 곤란", f: ["trouble"], lv: 2 },
  { w: "true", p: "형", m: "사실인, 진짜의", f: ["true"], lv: 1 },
  { w: "trust", p: "동", m: "믿다, 신뢰(하다)", f: ["trust"], lv: 2 },
  { w: "try", p: "동", m: "노력하다, 시도하다", f: ["try", "trying"], lv: 1 },
  { w: "Tuesday", p: "명", m: "화요일", f: ["tuesday", "tuesdays"], lv: 1 },
  { w: "tuna", p: "명", m: "참치", f: ["tuna"], lv: 2 },
  { w: "tunnel", p: "명", m: "터널", f: ["tunnel"], lv: 2 },
  { w: "turn", p: "동", m: "돌다, 돌리다, 차례", f: ["turn", "turned", "turning"], lv: 1 },
  { w: "turtle", p: "명", m: "거북", f: ["turtles"], lv: 1 },
  { w: "twice", p: "부", m: "두 번, 두 배로", f: ["twice"], lv: 1 },
  { w: "two", p: "명", m: "2, 둘", f: ["two"], lv: 1 },
  { w: "type", p: "명", m: "유형, 종류", f: ["type", "types"], lv: 2 },
  { w: "typhoon", p: "명", m: "태풍", f: ["typhoon"], lv: 2 },
  { w: "ultraviolet", p: "형", m: "자외선의, 자외선(UV)", f: ["ultra", "violet", "uv"], lv: 3 },
  { w: "umbrella", p: "명", m: "우산", f: ["umbrella"], lv: 1 },
  { w: "undersea", p: "형", m: "해저의, 바닷속의", f: ["undersea"], lv: 3 },
  { w: "understand", p: "동", m: "이해하다", f: ["understand"], lv: 1 },
  { w: "understanding", p: "명", m: "이해, 이해심 있는", f: ["understanding"], lv: 2 },
  { w: "underwater", p: "형", m: "물속의, 수중의", f: ["underwater"], lv: 2 },
  { w: "unexpected", p: "형", m: "예상치 못한", f: ["unexpected"], lv: 2 },
  { w: "unexpectedly", p: "부", m: "뜻밖에, 예상외로", f: ["unexpectedly"], lv: 3 },
  { w: "unforgettable", p: "형", m: "잊지 못할", f: ["unforgettable"], lv: 3 },
  { w: "unhappy", p: "형", m: "불행한, 불만스러운", f: ["unhappy"], lv: 1 },
  { w: "uniform", p: "명", m: "제복, 유니폼", f: ["uniform", "uniforms"], lv: 2 },
  { w: "unique", p: "형", m: "독특한, 유일한", f: ["unique"], lv: 2 },
  { w: "university", p: "명", m: "대학교", f: ["university"], lv: 2 },
  { w: "unkindly", p: "부", m: "불친절하게", f: ["unkindly"], lv: 2 },
  { w: "unknown", p: "형", m: "알려지지 않은", f: ["unknown"], lv: 2 },
  { w: "unorganized", p: "형", m: "체계적이지 못한, 정리 안 된", f: ["unorganized"], lv: 3 },
  { w: "unprepared", p: "형", m: "준비가 안 된", f: ["unprepared"], lv: 3 },
  { w: "unwanted", p: "형", m: "원치 않는, 필요 없는", f: ["unwanted"], lv: 2 },
  { w: "up", p: "부", m: "위로, 위에", f: ["up"], lv: 1 },
  { w: "upcycling", p: "명", m: "업사이클링(새활용)", f: ["upcycling"], lv: 3 },
  { w: "upset", p: "형", m: "속상한, 화난", f: ["upset"], lv: 2 },
  { w: "upside", p: "명", m: "(upside down) 거꾸로, 위쪽", f: ["upside"], lv: 2 },
  { w: "usage", p: "명", m: "사용(량)", f: ["usage"], lv: 3 },
  { w: "use", p: "동", m: "사용하다, 사용", f: ["use", "used", "uses", "using"], lv: 1 },
  { w: "useful", p: "형", m: "유용한, 쓸모 있는", f: ["useful"], lv: 1 },
  { w: "usefulness", p: "명", m: "유용성", f: ["usefulness"], lv: 3 },
  { w: "useless", p: "형", m: "쓸모없는", f: ["useless"], lv: 2 },
  { w: "user", p: "명", m: "사용자", f: ["users"], lv: 2 },
  { w: "usually", p: "부", m: "보통, 대개", f: ["usually"], lv: 1 },
  { w: "vacation", p: "명", m: "방학, 휴가", f: ["vacation"], lv: 1 },
  { w: "value", p: "명", m: "가치, 소중히 여기다", f: ["value"], lv: 2 },
  { w: "variety", p: "명", m: "다양성, 여러 가지", f: ["variety"], lv: 2 },
  { w: "various", p: "형", m: "다양한, 여러 가지의", f: ["various"], lv: 2 },
  { w: "vegetable", p: "명", m: "채소", f: ["vegetable", "vegetables"], lv: 1 },
  { w: "view", p: "명", m: "경치, 견해, 보다", f: ["view"], lv: 2 },
  { w: "village", p: "명", m: "마을", f: ["village"], lv: 1 },
  { w: "violate", p: "동", m: "위반하다, 어기다", f: ["violate"], lv: 3 },
  { w: "visit", p: "동", m: "방문하다", f: ["visit", "visited", "visiting"], lv: 1 },
  { w: "visitor", p: "명", m: "방문객", f: ["visitor", "visitors"], lv: 1 },
  { w: "vitamin", p: "명", m: "비타민", f: ["vitamins"], lv: 1 },
  { w: "volume", p: "명", m: "음량, 부피, 양", f: ["volume"], lv: 2 },
  { w: "volunteer", p: "명", m: "자원봉사자, 자원봉사하다", f: ["volunteer", "volunteered", "volunteering", "volunteers"], lv: 2 },
  { w: "wait", p: "동", m: "기다리다", f: ["wait", "waiting"], lv: 1 },
  { w: "wake", p: "동", m: "깨다, 깨우다", f: ["wake", "woke"], lv: 1 },
  { w: "walk", p: "동", m: "걷다, 산책", f: ["walk", "walking"], lv: 1 },
  { w: "wall", p: "명", m: "벽", f: ["wall", "walls"], lv: 1 },
  { w: "wallet", p: "명", m: "지갑", f: ["wallets"], lv: 1 },
  { w: "want", p: "동", m: "원하다", f: ["want", "wanted", "wants"], lv: 1 },
  { w: "warm", p: "형", m: "따뜻한", f: ["warm", "warming"], lv: 1 },
  { w: "warn", p: "동", m: "경고하다", f: ["warn"], lv: 2 },
  { w: "wash", p: "동", m: "씻다, 빨다", f: ["wash", "washed", "washing"], lv: 1 },
  { w: "waste", p: "명", m: "쓰레기, 낭비(하다)", f: ["waste", "wasting"], lv: 2 },
  { w: "watch", p: "동", m: "보다, 지켜보다, 시계", f: ["watch", "watched", "watching"], lv: 1 },
  { w: "water", p: "명", m: "물", f: ["water"], lv: 1 },
  { w: "watermelon", p: "명", m: "수박", f: ["watermelon"], lv: 1, u: true },
  { w: "way", p: "명", m: "방법, 길", f: ["way", "ways"], lv: 1 },
  { w: "weak", p: "형", m: "약한", f: ["weak"], lv: 1 },
  { w: "wear", p: "동", m: "입다, 착용하다", f: ["wear", "wearing"], lv: 1 },
  { w: "wearable", p: "형", m: "착용할 수 있는", f: ["wearable"], lv: 3 },
  { w: "weather", p: "명", m: "날씨", f: ["weather"], lv: 1 },
  { w: "website", p: "명", m: "웹사이트", f: ["website"], lv: 1 },
  { w: "week", p: "명", m: "주, 일주일", f: ["week", "weeks"], lv: 1 },
  { w: "weekend", p: "명", m: "주말", f: ["weekend", "weekends"], lv: 1 },
  { w: "weekly", p: "형", m: "매주의, 주간의", f: ["weekly"], lv: 2 },
  { w: "weight", p: "명", m: "무게, 체중", f: ["weight"], lv: 2 },
  { w: "welcome", p: "감", m: "환영합니다, 환영하다", f: ["welcome"], lv: 1 },
  { w: "well", p: "부", m: "잘, 글쎄", f: ["well"], lv: 1 },
  { w: "go", p: "동", m: "가다", f: ["went"], lv: 1 },
  { w: "west", p: "명", m: "서쪽, 서쪽의", f: ["west"], lv: 1 },
  { w: "western", p: "형", m: "서양의, 서쪽의", f: ["western"], lv: 2 },
  { w: "wet", p: "형", m: "젖은", f: ["wet"], lv: 1 },
  { w: "whether", p: "접", m: "~인지 (아닌지)", f: ["whether"], lv: 2 },
  { w: "while", p: "접", m: "~하는 동안, ~인 반면", f: ["while"], lv: 2, u: true },
  { w: "white", p: "형", m: "흰, 하얀", f: ["white"], lv: 1 },
  { w: "whole", p: "형", m: "전체의, 모든", f: ["whole"], lv: 2 },
  { w: "wide", p: "형", m: "넓은, 다양한", f: ["wide"], lv: 1 },
  { w: "win", p: "동", m: "이기다, 얻다", f: ["win", "wins"], lv: 1 },
  { w: "wind", p: "명", m: "바람", f: ["wind"], lv: 1 },
  { w: "window", p: "명", m: "창문", f: ["window", "windows"], lv: 1 },
  { w: "winner", p: "명", m: "우승자, 승자", f: ["winner"], lv: 1 },
  { w: "winter", p: "명", m: "겨울", f: ["winter"], lv: 1 },
  { w: "wintertime", p: "명", m: "겨울철", f: ["wintertime"], lv: 2 },
  { w: "wisdom", p: "명", m: "지혜", f: ["wisdom"], lv: 2 },
  { w: "wise", p: "형", m: "현명한, 지혜로운", f: ["wise"], lv: 2 },
  { w: "wisely", p: "부", m: "현명하게", f: ["wisely"], lv: 2 },
  { w: "wish", p: "동", m: "바라다, 소원", f: ["wish"], lv: 1 },
  { w: "within", p: "전", m: "~안에, ~이내에", f: ["within"], lv: 2 },
  { w: "without", p: "전", m: "~없이", f: ["without"], lv: 1 },
  { w: "woman", p: "명", m: "여자, 여성", f: ["women"], lv: 1 },
  { w: "wonder", p: "동", m: "궁금해하다, 놀라움", f: ["wonder"], lv: 2 },
  { w: "wonderful", p: "형", m: "멋진, 훌륭한", f: ["wonderful"], lv: 1 },
  { w: "wood", p: "명", m: "나무, 목재", f: ["wood"], lv: 1 },
  { w: "word", p: "명", m: "단어, 말", f: ["word", "words"], lv: 1 },
  { w: "work", p: "동", m: "일하다, 작동하다, 효과가 있다", f: ["work", "worked", "working", "works"], lv: 1 },
  { w: "workshop", p: "명", m: "워크숍, 연수회", f: ["workshop"], lv: 2 },
  { w: "world", p: "명", m: "세계, 세상", f: ["world"], lv: 1 },
  { w: "worldwide", p: "부", m: "전 세계적으로", f: ["worldwide"], lv: 2 },
  { w: "worried", p: "형", m: "걱정하는", f: ["worried"], lv: 1 },
  { w: "worry", p: "동", m: "걱정하다, 걱정", f: ["worries", "worry", "worrying"], lv: 1 },
  { w: "bad", p: "형", m: "나쁜, 심한", f: ["worse"], lv: 1 },
  { w: "wow", p: "감", m: "와, 우와", f: ["wow"], lv: 1 },
  { w: "wrapping", p: "명", m: "포장(지)", f: ["wrapping"], lv: 2 },
  { w: "write", p: "동", m: "쓰다", f: ["write", "writing", "written"], lv: 1 },
  { w: "writer", p: "명", m: "작가, 글쓴이", f: ["writer"], lv: 1 },
  { w: "wrong", p: "형", m: "잘못된, 틀린", f: ["wrong"], lv: 1 },
  { w: "yeah", p: "감", m: "응, 그래", f: ["yeah"], lv: 1 },
  { w: "year", p: "명", m: "해, 년, 나이", f: ["year", "years"], lv: 1 },
  { w: "yell", p: "동", m: "소리치다, 고함치다", f: ["yell"], lv: 2 },
  { w: "yellow", p: "형", m: "노란, 노란색", f: ["yellow"], lv: 1 },
  { w: "yesterday", p: "부", m: "어제", f: ["yesterday"], lv: 1 },
  { w: "yoga", p: "명", m: "요가", f: ["yoga"], lv: 1 },
  { w: "young", p: "형", m: "어린, 젊은", f: ["young"], lv: 1 },
  { w: "zero", p: "명", m: "0, 영", f: ["zero"], lv: 1 },
  { w: "zone", p: "명", m: "구역, 지역", f: ["zone"], lv: 2 },
  { w: "zoo", p: "명", m: "동물원", f: ["zoo"], lv: 1 },
  { w: "suffer from", p: "숙어", m: "~로 고통받다, ~을 앓다", f: ["suffer from", "suffering from"], lv: 2, ph: true, u: true },
  { w: "take care of", p: "숙어", m: "~을 돌보다, 처리하다", f: ["take care of"], lv: 1, ph: true, u: true },
  { w: "thanks to", p: "숙어", m: "~덕분에", f: ["thanks to"], lv: 2, ph: true, u: true },
  { w: "take part in", p: "숙어", m: "~에 참가하다", f: ["take part in"], lv: 2, ph: true, u: true },
  { w: "throw away", p: "숙어", m: "버리다", f: ["throw away"], lv: 1, ph: true, u: true },
  { w: "Well begun is half done", p: "속담", m: "시작이 반이다", f: ["well begun is half done"], lv: 2, ph: true, u: true },
  { w: "The more, the better", p: "속담", m: "많을수록 좋다", f: ["the more, the better"], lv: 2, ph: true, u: true },
  { w: "time flies like an arrow", p: "속담", m: "세월은 화살처럼 빠르다", f: ["time flies like an arrow"], lv: 2, ph: true, u: true },
  { w: "When in Rome, do as the Romans do", p: "속담", m: "로마에 가면 로마법을 따르라", f: ["when in rome, do as the romans do"], lv: 2, ph: true, u: true },
  { w: "Two heads are better than one", p: "속담", m: "백지장도 맞들면 낫다", f: ["two heads are better than one"], lv: 2, ph: true, u: true }
);
