// 영어 기출 단어장 (파트 2)
(window.ENGLISH_VOCAB = window.ENGLISH_VOCAB || []).push(
  { w: "coal", p: "명", m: "석탄", f: ["coal"], lv: 2 },
  { w: "coding", p: "명", m: "코딩, 프로그래밍", f: ["coding"], lv: 2 },
  { w: "coffee", p: "명", m: "커피", f: ["coffee"], lv: 1 },
  { w: "coke", p: "명", m: "콜라", f: ["coke"], lv: 1 },
  { w: "cold", p: "형", m: "추운, 차가운, 감기", f: ["cold", "colder"], lv: 1 },
  { w: "collect", p: "동", m: "모으다, 수집하다", f: ["collect"], lv: 2 },
  { w: "collection", p: "명", m: "수집, 수집품", f: ["collection"], lv: 2 },
  { w: "college", p: "명", m: "대학, 전문학교", f: ["college"], lv: 2 },
  { w: "color", p: "명", m: "색깔, 색칠하다", f: ["color", "colors", "coloring"], lv: 1 },
  { w: "colorful", p: "형", m: "다채로운, 화려한", f: ["colorful"], lv: 1 },
  { w: "come", p: "동", m: "오다", f: ["come", "comes", "coming"], lv: 1 },
  { w: "comedy", p: "명", m: "코미디, 희극", f: ["comedy"], lv: 2 },
  { w: "comfortable", p: "형", m: "편안한", f: ["comfortable"], lv: 2 },
  { w: "comfort", p: "명", m: "편안함, 위안", f: ["comforts"], lv: 2 },
  { w: "comic", p: "형", m: "만화의, 웃기는", f: ["comic"], lv: 2 },
  { w: "comment", p: "명", m: "의견, 논평", f: ["comment"], lv: 2 },
  { w: "commercial", p: "형", m: "상업의, 광고", f: ["commercial"], lv: 3 },
  { w: "common", p: "형", m: "흔한, 공통의", f: ["common"], lv: 2 },
  { w: "communication", p: "명", m: "의사소통", f: ["communication"], lv: 2 },
  { w: "communicator", p: "명", m: "전달자, 소통하는 사람", f: ["communicators"], lv: 3 },
  { w: "community", p: "명", m: "지역 사회, 공동체", f: ["community"], lv: 2 },
  { w: "company", p: "명", m: "회사, 동행", f: ["company", "companies"], lv: 2 },
  { w: "compare", p: "동", m: "비교하다", f: ["compared", "comparing"], lv: 2 },
  { w: "competition", p: "명", m: "대회, 경쟁", f: ["competition"], lv: 2 },
  { w: "complete", p: "동", m: "완성하다, 완전한", f: ["complete"], lv: 2 },
  { w: "computer", p: "명", m: "컴퓨터", f: ["computer", "computers"], lv: 1 },
  { w: "concentrate", p: "동", m: "집중하다", f: ["concentrate"], lv: 2 },
  { w: "concern", p: "명", m: "걱정, 관심", f: ["concern"], lv: 2 },
  { w: "concerned", p: "형", m: "걱정하는, 관심 있는", f: ["concerned"], lv: 2 },
  { w: "concert", p: "명", m: "음악회, 공연", f: ["concert", "concerts"], lv: 1 },
  { w: "condition", p: "명", m: "상태, 조건", f: ["condition", "conditions"], lv: 2 },
  { w: "confidence", p: "명", m: "자신감, 신뢰", f: ["confidence"], lv: 2, u: true },
  { w: "confident", p: "형", m: "자신감 있는", f: ["confident"], lv: 2 },
  { w: "confirm", p: "동", m: "확인하다", f: ["confirm"], lv: 2 },
  { w: "conflict", p: "명", m: "갈등, 충돌", f: ["conflict"], lv: 3 },
  { w: "connect", p: "동", m: "연결하다", f: ["connected"], lv: 2 },
  { w: "consider", p: "동", m: "여기다, 고려하다", f: ["consider", "considered"], lv: 2 },
  { w: "consist", p: "동", m: "(~로) 이루어지다", f: ["consist", "consists"], lv: 3 },
  { w: "consume", p: "동", m: "소비하다", f: ["consume"], lv: 3 },
  { w: "consumer", p: "명", m: "소비자", f: ["consumers"], lv: 2 },
  { w: "consumption", p: "명", m: "소비", f: ["consumption"], lv: 3 },
  { w: "contact", p: "명", m: "연락, 연락하다", f: ["contact"], lv: 2 },
  { w: "contain", p: "동", m: "포함하다, 담고 있다", f: ["contains"], lv: 2 },
  { w: "contemporary", p: "형", m: "현대의, 동시대의", f: ["contemporary"], lv: 3 },
  { w: "content", p: "명", m: "내용, 내용물", f: ["contents"], lv: 2 },
  { w: "contest", p: "명", m: "대회, 경연", f: ["contest"], lv: 2 },
  { w: "contestant", p: "명", m: "참가자", f: ["contestants"], lv: 3 },
  { w: "continue", p: "동", m: "계속하다", f: ["continue"], lv: 2 },
  { w: "contrast", p: "명", m: "대조, 차이", f: ["contrast"], lv: 3 },
  { w: "contribute", p: "동", m: "기여하다, 원인이 되다", f: ["contributing"], lv: 3 },
  { w: "control", p: "동", m: "조절하다, 통제", f: ["control"], lv: 2 },
  { w: "convenience", p: "명", m: "편리, 편의", f: ["convenience"], lv: 3 },
  { w: "convenient", p: "형", m: "편리한", f: ["convenient"], lv: 2 },
  { w: "conversation", p: "명", m: "대화", f: ["conversation"], lv: 2 },
  { w: "cook", p: "동", m: "요리하다, 요리사", f: ["cook", "cooked", "cooking"], lv: 1 },
  { w: "cool", p: "형", m: "시원한, 멋진", f: ["cool"], lv: 1 },
  { w: "cooperation", p: "명", m: "협력, 협동", f: ["cooperation"], lv: 3 },
  { w: "copy", p: "명", m: "복사본, 베끼다", f: ["copy"], lv: 2 },
  { w: "corner", p: "명", m: "모퉁이, 구석", f: ["corner"], lv: 1 },
  { w: "correct", p: "형", m: "올바른, 정확한", f: ["correct"], lv: 2 },
  { w: "costume", p: "명", m: "의상, 복장", f: ["costumes"], lv: 2 },
  { w: "counselor", p: "명", m: "상담사", f: ["counselor"], lv: 3 },
  { w: "count", p: "동", m: "세다, 중요하다", f: ["count"], lv: 1 },
  { w: "country", p: "명", m: "나라, 시골", f: ["country", "countries"], lv: 1 },
  { w: "couple", p: "명", m: "두어 개, 부부, 커플", f: ["couple"], lv: 2 },
  { w: "course", p: "명", m: "강좌, 과정, 코스", f: ["course", "courses"], lv: 2 },
  { w: "court", p: "명", m: "경기장, 코트, 법정", f: ["court"], lv: 2 },
  { w: "cover", p: "동", m: "덮다, 표지", f: ["cover", "covered"], lv: 1 },
  { w: "crash", p: "동", m: "충돌하다, 부딪치다", f: ["crash"], lv: 2 },
  { w: "cream", p: "명", m: "크림", f: ["cream"], lv: 1 },
  { w: "create", p: "동", m: "만들다, 창조하다", f: ["create", "created"], lv: 2 },
  { w: "creative", p: "형", m: "창의적인", f: ["creative"], lv: 2 },
  { w: "creature", p: "명", m: "생물, 동물", f: ["creatures"], lv: 2 },
  { w: "credit", p: "명", m: "신용, 학점", f: ["credit"], lv: 2 },
  { w: "critical", p: "형", m: "비판적인, 중요한", f: ["critical"], lv: 3 },
  { w: "criticize", p: "동", m: "비판하다", f: ["criticized"], lv: 3 },
  { w: "crop", p: "명", m: "농작물", f: ["crops"], lv: 2 },
  { w: "cross", p: "동", m: "건너다", f: ["cross"], lv: 1 },
  { w: "crowded", p: "형", m: "붐비는, 혼잡한", f: ["crowded"], lv: 2 },
  { w: "crush", p: "동", m: "으깨다, 부수다", f: ["crushed"], lv: 3 },
  { w: "cry", p: "동", m: "울다, 외치다", f: ["crying"], lv: 1 },
  { w: "cultivation", p: "명", m: "재배, 경작", f: ["cultivation"], lv: 3 },
  { w: "cultural", p: "형", m: "문화의", f: ["cultural"], lv: 2 },
  { w: "culture", p: "명", m: "문화", f: ["culture", "cultures"], lv: 2 },
  { w: "cup", p: "명", m: "컵, 잔", f: ["cup"], lv: 1 },
  { w: "current", p: "형", m: "현재의, 흐름", f: ["current"], lv: 3 },
  { w: "custom", p: "명", m: "관습, 풍습", f: ["custom", "customs"], lv: 2 },
  { w: "customer", p: "명", m: "손님, 고객", f: ["customer", "customers"], lv: 2 },
  { w: "cut", p: "동", m: "자르다, 줄이다", f: ["cut"], lv: 1 },
  { w: "cycling", p: "명", m: "자전거 타기", f: ["cycling"], lv: 2 },
  { w: "dad", p: "명", m: "아빠", f: ["dad"], lv: 1 },
  { w: "daily", p: "형", m: "매일의, 일상의", f: ["daily"], lv: 2 },
  { w: "damage", p: "명", m: "피해, 손상, 손상시키다", f: ["damage", "damaged", "damages"], lv: 2 },
  { w: "dance", p: "동", m: "춤추다, 춤", f: ["dance"], lv: 1 },
  { w: "dancer", p: "명", m: "무용수, 춤꾼", f: ["dancer", "dancers"], lv: 1 },
  { w: "danger", p: "명", m: "위험", f: ["danger", "dangers"], lv: 2 },
  { w: "dangerous", p: "형", m: "위험한", f: ["dangerous"], lv: 1 },
  { w: "dark", p: "형", m: "어두운, 짙은", f: ["dark"], lv: 1, u: true },
  { w: "date", p: "명", m: "날짜, 기간, 데이트", f: ["date"], lv: 1 },
  { w: "day", p: "명", m: "날, 하루, 낮", f: ["day", "days"], lv: 1 },
  { w: "dead", p: "형", m: "죽은", f: ["dead"], lv: 1 },
  { w: "deadline", p: "명", m: "마감 기한", f: ["deadline"], lv: 2 },
  { w: "deal", p: "명", m: "거래, 처리하다", f: ["deal"], lv: 2 },
  { w: "dear", p: "형", m: "~에게(편지), 소중한", f: ["dear"], lv: 1 },
  { w: "decade", p: "명", m: "10년", f: ["decades"], lv: 3 },
  { w: "December", p: "명", m: "12월", f: ["december"], lv: 1 },
  { w: "decide", p: "동", m: "결정하다, 결심하다", f: ["decide", "decided"], lv: 1 },
  { w: "decision", p: "명", m: "결정, 결심", f: ["decision"], lv: 2, u: true },
  { w: "decorate", p: "동", m: "장식하다, 꾸미다", f: ["decorate"], lv: 2, u: true },
  { w: "decrease", p: "동", m: "감소하다, 감소", f: ["decrease"], lv: 2 },
  { w: "deep", p: "형", m: "깊은", f: ["deep"], lv: 1 },
  { w: "deeply", p: "부", m: "깊이, 매우", f: ["deeply"], lv: 2 },
  { w: "definitely", p: "부", m: "분명히, 확실히", f: ["definitely"], lv: 2 },
  { w: "delay", p: "명", m: "지연, 연기하다", f: ["delay", "delays"], lv: 2 },
  { w: "delicious", p: "형", m: "맛있는", f: ["delicious"], lv: 1 },
  { w: "delighted", p: "형", m: "기쁜, 아주 즐거운", f: ["delighted"], lv: 2 },
  { w: "deliver", p: "동", m: "배달하다, 전달하다", f: ["deliver", "delivered"], lv: 2 },
  { w: "delivery", p: "명", m: "배달", f: ["delivery", "deliveries"], lv: 2 },
  { w: "demand", p: "명", m: "수요, 요구", f: ["demand"], lv: 3 },
  { w: "depart", p: "동", m: "출발하다, 떠나다", f: ["depart"], lv: 2 },
  { w: "depend", p: "동", m: "의존하다, ~에 달려 있다", f: ["depend", "depends"], lv: 2 },
  { w: "deposit", p: "명", m: "보증금, 예치금", f: ["deposit"], lv: 3 },
  { w: "depressed", p: "형", m: "우울한", f: ["depressed"], lv: 2 },
  { w: "describe", p: "동", m: "묘사하다, 설명하다", f: ["describe"], lv: 2 },
  { w: "description", p: "명", m: "설명, 묘사", f: ["description"], lv: 2 },
  { w: "desert", p: "명", m: "사막", f: ["desert"], lv: 2 },
  { w: "deserve", p: "동", m: "~할 자격이 있다", f: ["deserve"], lv: 3 },
  { w: "design", p: "명", m: "디자인, 설계하다", f: ["design", "designed"], lv: 2 },
  { w: "designer", p: "명", m: "디자이너", f: ["designer", "designers"], lv: 2 },
  { w: "desire", p: "명", m: "욕구, 바라다", f: ["desire"], lv: 3 },
  { w: "desk", p: "명", m: "책상, 창구", f: ["desk"], lv: 1 },
  { w: "despite", p: "전", m: "~에도 불구하고", f: ["despite"], lv: 2, u: true },
  { w: "dessert", p: "명", m: "후식, 디저트", f: ["dessert"], lv: 1 },
  { w: "destroy", p: "동", m: "파괴하다", f: ["destroy", "destroying"], lv: 2 },
  { w: "detail", p: "명", m: "세부 사항", f: ["detail"], lv: 2 },
  { w: "develop", p: "동", m: "발전시키다, 개발하다", f: ["develop"], lv: 2 },
  { w: "dictionary", p: "명", m: "사전", f: ["dictionary"], lv: 1 },
  { w: "die", p: "동", m: "죽다", f: ["die"], lv: 1 },
  { w: "diet", p: "명", m: "식단, 식습관, 다이어트", f: ["diet", "diets"], lv: 2 },
  { w: "difference", p: "명", m: "차이, 다름", f: ["difference", "differences"], lv: 2 },
  { w: "different", p: "형", m: "다른, 다양한", f: ["different"], lv: 1 },
  { w: "difficult", p: "형", m: "어려운", f: ["difficult"], lv: 1, u: true },
  { w: "difficulty", p: "명", m: "어려움, 곤란", f: ["difficulty", "difficulties"], lv: 2 },
  { w: "digestion", p: "명", m: "소화", f: ["digestion"], lv: 3 },
  { w: "dining", p: "명", m: "식사", f: ["dining"], lv: 2 },
  { w: "dinner", p: "명", m: "저녁 식사", f: ["dinner"], lv: 1 },
  { w: "dioxide", p: "명", m: "이산화물", f: ["dioxide"], lv: 3 },
  { w: "dirty", p: "형", m: "더러운", f: ["dirty"], lv: 1 },
  { w: "disappointed", p: "형", m: "실망한", f: ["disappointed"], lv: 2 },
  { w: "disaster", p: "명", m: "재난, 재해", f: ["disasters"], lv: 2 },
  { w: "discount", p: "명", m: "할인, 할인하다", f: ["discount", "discounted"], lv: 2 },
  { w: "discourage", p: "동", m: "막다, 낙담시키다", f: ["discourage"], lv: 3 },
  { w: "discover", p: "동", m: "발견하다", f: ["discovered"], lv: 2 },
  { w: "disease", p: "명", m: "질병", f: ["disease"], lv: 2 },
  { w: "dish", p: "명", m: "요리, 접시", f: ["dish", "dishes"], lv: 1 },
  { w: "display", p: "동", m: "전시하다, 진열하다", f: ["displayed"], lv: 2 },
  { w: "distance", p: "명", m: "거리", f: ["distance"], lv: 2 },
  { w: "distract", p: "동", m: "(주의를) 산만하게 하다", f: ["distracts"], lv: 3 },
  { w: "dive", p: "동", m: "잠수하다, 뛰어들다", f: ["dive"], lv: 2 },
  { w: "diver", p: "명", m: "잠수부, 다이버", f: ["divers"], lv: 2 },
  { w: "diverse", p: "형", m: "다양한", f: ["diverse"], lv: 3 },
  { w: "divide", p: "동", m: "나누다", f: ["divides"], lv: 2 },
  { w: "diving", p: "명", m: "다이빙, 잠수", f: ["diving"], lv: 2 },
  { w: "DIY", p: "명", m: "직접 만들기", f: ["diy"], lv: 2 },
  { w: "doctor", p: "명", m: "의사", f: ["doctor"], lv: 1 },
  { w: "document", p: "명", m: "서류, 문서", f: ["documents"], lv: 2 },
  { w: "dog", p: "명", m: "개", f: ["dog", "dogs"], lv: 1 },
  { w: "doll", p: "명", m: "인형", f: ["doll", "dolls"], lv: 1 },
  { w: "dollar", p: "명", m: "달러", f: ["dollars"], lv: 1 },
  { w: "donate", p: "동", m: "기부하다", f: ["donate", "donated"], lv: 2 },
  { w: "donation", p: "명", m: "기부", f: ["donation"], lv: 2 },
  { w: "door", p: "명", m: "문", f: ["door"], lv: 1 },
  { w: "down", p: "부", m: "아래로", f: ["down"], lv: 1 },
  { w: "downstairs", p: "부", m: "아래층으로", f: ["downstairs"], lv: 2 },
  { w: "downtown", p: "명", m: "시내, 중심가", f: ["downtown"], lv: 2 },
  { w: "draw", p: "동", m: "그리다, 끌다", f: ["draw", "drew"], lv: 1 },
  { w: "dream", p: "명", m: "꿈, 꿈꾸다", f: ["dream", "dreamed"], lv: 1 },
  { w: "dreamer", p: "명", m: "꿈꾸는 사람", f: ["dreamers"], lv: 2 },
  { w: "dress", p: "명", m: "드레스, 옷을 입다", f: ["dress"], lv: 1 },
  { w: "dried", p: "형", m: "말린, 건조한", f: ["dried"], lv: 2 },
  { w: "drink", p: "동", m: "마시다, 음료", f: ["drink", "drinking", "drinks"], lv: 1 },
  { w: "drive", p: "동", m: "운전하다", f: ["drive", "driving"], lv: 1 },
  { w: "driver", p: "명", m: "운전자", f: ["drivers"], lv: 1 },
  { w: "drought", p: "명", m: "가뭄", f: ["drought"], lv: 3 },
  { w: "dry", p: "형", m: "건조한, 말리다", f: ["dry"], lv: 1 },
  { w: "dryer", p: "명", m: "건조기, 드라이어", f: ["dryer", "dryers"], lv: 2 },
  { w: "due", p: "형", m: "~ 때문인, 예정된", f: ["due"], lv: 2 },
  { w: "duty", p: "명", m: "의무, 임무", f: ["duty"], lv: 2, u: true },
  { w: "early", p: "형", m: "이른, 일찍", f: ["early", "earlier"], lv: 1 },
  { w: "earth", p: "명", m: "지구, 땅", f: ["earth"], lv: 1 },
  { w: "earthquake", p: "명", m: "지진", f: ["earthquake"], lv: 2 },
  { w: "easy", p: "형", m: "쉬운", f: ["easy", "easier"], lv: 1, u: true },
  { w: "easily", p: "부", m: "쉽게", f: ["easily"], lv: 1 },
  { w: "eat", p: "동", m: "먹다", f: ["eat", "eaten", "eating"], lv: 1 },
  { w: "eco", p: "형", m: "환경의, 친환경(eco-friendly)", f: ["eco"], lv: 2 },
  { w: "economy", p: "명", m: "경제", f: ["economy"], lv: 2 },
  { w: "ecosystem", p: "명", m: "생태계", f: ["ecosystem"], lv: 3 },
  { w: "education", p: "명", m: "교육", f: ["education"], lv: 2 },
  { w: "effect", p: "명", m: "효과, 영향", f: ["effect", "effects"], lv: 2 },
  { w: "effectively", p: "부", m: "효과적으로", f: ["effectively"], lv: 2 },
  { w: "efficient", p: "형", m: "효율적인", f: ["efficient"], lv: 3 },
  { w: "efficiently", p: "부", m: "효율적으로", f: ["efficiently"], lv: 3 },
  { w: "effort", p: "명", m: "노력", f: ["effort"], lv: 2, u: true },
  { w: "egg", p: "명", m: "달걀", f: ["eggs"], lv: 1 },
  { w: "eight", p: "명", m: "8, 여덟", f: ["eight"], lv: 1 },
  { w: "electric", p: "형", m: "전기의", f: ["electric"], lv: 2 },
  { w: "electricity", p: "명", m: "전기", f: ["electricity"], lv: 2 },
  { w: "element", p: "명", m: "요소, 원소", f: ["element"], lv: 3 },
  { w: "elevator", p: "명", m: "엘리베이터", f: ["elevator"], lv: 1 },
  { w: "eleven", p: "명", m: "11, 열하나", f: ["eleven"], lv: 1 },
  { w: "else", p: "부", m: "그 밖의, 다른", f: ["else"], lv: 1 },
  { w: "email", p: "명", m: "이메일", f: ["email"], lv: 1 },
  { w: "emergency", p: "명", m: "비상, 응급", f: ["emergency"], lv: 2 },
  { w: "emotion", p: "명", m: "감정", f: ["emotion"], lv: 2 },
  { w: "employee", p: "명", m: "직원, 종업원", f: ["employee", "employees"], lv: 2 },
  { w: "empty", p: "형", m: "비어 있는", f: ["empty"], lv: 2, u: true },
  { w: "encourage", p: "동", m: "격려하다, 권장하다", f: ["encourage", "encouraged", "encourages", "encouraging"], lv: 2 },
  { w: "end", p: "명", m: "끝, 끝나다", f: ["end"], lv: 1 },
  { w: "endless", p: "형", m: "끝없는", f: ["endless"], lv: 2 },
  { w: "endure", p: "동", m: "견디다, 참다", f: ["endure"], lv: 3 },
  { w: "energetic", p: "형", m: "활기찬, 정력적인", f: ["energetic"], lv: 2 },
  { w: "energy", p: "명", m: "에너지, 힘", f: ["energy"], lv: 1 },
  { w: "engineer", p: "명", m: "기술자, 엔지니어", f: ["engineer"], lv: 2 },
  { w: "English", p: "명", m: "영어, 영국의", f: ["english"], lv: 1 },
  { w: "enhance", p: "동", m: "높이다, 향상시키다", f: ["enhance"], lv: 3 },
  { w: "enjoy", p: "동", m: "즐기다", f: ["enjoy", "enjoyed", "enjoying"], lv: 1 },
  { w: "enjoyment", p: "명", m: "즐거움", f: ["enjoyment"], lv: 2 },
  { w: "enlarge", p: "동", m: "확대하다, 넓히다", f: ["enlarge"], lv: 3 },
  { w: "enough", p: "형", m: "충분한, 충분히", f: ["enough"], lv: 1 },
  { w: "enroll", p: "동", m: "등록하다, 입학하다", f: ["enroll"], lv: 3 },
  { w: "enter", p: "동", m: "들어가다, 입장하다", f: ["entering"], lv: 1 },
  { w: "enthusiastic", p: "형", m: "열정적인, 열렬한", f: ["enthusiastic"], lv: 3 },
  { w: "entrance", p: "명", m: "입장, 입구", f: ["entrance"], lv: 2 },
  { w: "environment", p: "명", m: "환경", f: ["environment", "environments"], lv: 2 },
  { w: "environmental", p: "형", m: "환경의", f: ["environmental"], lv: 2 },
  { w: "envy", p: "명", m: "부러움, 부러워하다", f: ["envy"], lv: 3 },
  { w: "equal", p: "형", m: "동등한, 평등한", f: ["equal"], lv: 2 },
  { w: "eraser", p: "명", m: "지우개", f: ["eraser"], lv: 1 },
  { w: "especially", p: "부", m: "특히", f: ["especially"], lv: 2 },
  { w: "evaluate", p: "동", m: "평가하다", f: ["evaluate"], lv: 3 },
  { w: "even", p: "부", m: "~조차, 훨씬", f: ["even"], lv: 1 },
  { w: "evening", p: "명", m: "저녁", f: ["evening"], lv: 1 },
  { w: "event", p: "명", m: "행사, 사건", f: ["event", "events"], lv: 2 },
  { w: "eventually", p: "부", m: "결국, 마침내", f: ["eventually"], lv: 3 },
  { w: "ever", p: "부", m: "지금까지, 언젠가", f: ["ever"], lv: 1 },
  { w: "everyday", p: "형", m: "일상의, 매일의", f: ["everyday"], lv: 1 },
  { w: "everyone", p: "대", m: "모든 사람", f: ["everyone"], lv: 1 },
  { w: "everything", p: "대", m: "모든 것", f: ["everything"], lv: 1 },
  { w: "everywhere", p: "부", m: "모든 곳에", f: ["everywhere"], lv: 1 },
  { w: "evidence", p: "명", m: "증거", f: ["evidence"], lv: 3 },
  { w: "exactly", p: "부", m: "정확히, 바로 그렇다", f: ["exactly"], lv: 2 },
  { w: "exam", p: "명", m: "시험", f: ["exam"], lv: 1 },
  { w: "example", p: "명", m: "예, 보기", f: ["example", "examples"], lv: 1 },
  { w: "except", p: "전", m: "~을 제외하고", f: ["except"], lv: 2, u: true },
  { w: "exchange", p: "명", m: "교환, 교환하다", f: ["exchange"], lv: 2 },
  { w: "excited", p: "형", m: "신이 난, 흥분한", f: ["excited"], lv: 1 },
  { w: "exciting", p: "형", m: "신나는, 흥미진진한", f: ["exciting"], lv: 1 },
  { w: "excuse", p: "동", m: "용서하다, 변명", f: ["excuse"], lv: 2 },
  { w: "exercise", p: "명", m: "운동, 운동하다", f: ["exercise", "exercises", "exercising"], lv: 1 },
  { w: "exhibition", p: "명", m: "전시회", f: ["exhibition"], lv: 3 },
  { w: "exist", p: "동", m: "존재하다", f: ["existed", "exists"], lv: 2 },
  { w: "exit", p: "명", m: "출구, 나가다", f: ["exit"], lv: 2 },
  { w: "expect", p: "동", m: "예상하다, 기대하다", f: ["expected"], lv: 2 },
  { w: "expensive", p: "형", m: "비싼", f: ["expensive"], lv: 1 },
  { w: "experience", p: "명", m: "경험, 경험하다", f: ["experience"], lv: 2, u: true },
  { w: "expert", p: "명", m: "전문가", f: ["experts"], lv: 2 },
  { w: "explain", p: "동", m: "설명하다", f: ["explain"], lv: 2 },
  { w: "explanation", p: "명", m: "설명", f: ["explanations"], lv: 2 },
  { w: "explore", p: "동", m: "탐험하다, 탐구하다", f: ["explore"], lv: 2 },
  { w: "explorer", p: "명", m: "탐험가", f: ["explorers"], lv: 2 },
  { w: "expo", p: "명", m: "박람회, 엑스포", f: ["expo"], lv: 2 },
  { w: "expose", p: "동", m: "노출시키다, 드러내다", f: ["exposed"], lv: 3 },
  { w: "express", p: "동", m: "표현하다", f: ["express"], lv: 2 },
  { w: "expression", p: "명", m: "표현", f: ["expression"], lv: 2 },
  { w: "extend", p: "동", m: "연장하다, 늘리다", f: ["extend"], lv: 3 },
  { w: "eye", p: "명", m: "눈", f: ["eyes"], lv: 1 },
  { w: "face", p: "동", m: "직면하다, 얼굴", f: ["face", "facing"], lv: 1 },
  { w: "fact", p: "명", m: "사실", f: ["fact"], lv: 1 },
  { w: "factor", p: "명", m: "요인, 요소", f: ["factors"], lv: 3 },
  { w: "fail", p: "동", m: "실패하다, 떨어지다", f: ["fail"], lv: 2 },
  { w: "fair", p: "명", m: "박람회, 공정한", f: ["fair"], lv: 2 },
  { w: "fall", p: "동", m: "떨어지다, 넘어지다, 가을", f: ["fall", "falling", "fell"], lv: 1 },
  { w: "familiar", p: "형", m: "친숙한, 익숙한", f: ["familiar"], lv: 2 },
  { w: "family", p: "명", m: "가족", f: ["family"], lv: 1 },
  { w: "famous", p: "형", m: "유명한", f: ["famous"], lv: 1 },
  { w: "fantastic", p: "형", m: "환상적인, 멋진", f: ["fantastic"], lv: 1 },
  { w: "far", p: "부", m: "멀리, 먼", f: ["far"], lv: 1 },
  { w: "fascinating", p: "형", m: "매혹적인, 아주 흥미로운", f: ["fascinating"], lv: 3 },
  { w: "fashion", p: "명", m: "패션, 유행", f: ["fashion"], lv: 2 },
  { w: "fast", p: "형", m: "빠른, 빨리", f: ["fast"], lv: 1 },
  { w: "fasten", p: "동", m: "매다, 고정하다", f: ["fasten"], lv: 3 },
  { w: "fat", p: "명", m: "지방, 뚱뚱한", f: ["fat"], lv: 1 },
  { w: "father", p: "명", m: "아버지", f: ["father"], lv: 1 },
  { w: "favor", p: "명", m: "부탁, 호의", f: ["favor"], lv: 2 },
  { w: "favorite", p: "형", m: "가장 좋아하는", f: ["favorite"], lv: 1 },
  { w: "fear", p: "명", m: "두려움, 공포", f: ["fear"], lv: 2 },
  { w: "feather", p: "명", m: "깃털", f: ["feathers"], lv: 2 },
  { w: "feature", p: "명", m: "특징, 특색", f: ["feature", "features"], lv: 2 },
  { w: "fee", p: "명", m: "요금, 수수료", f: ["fee"], lv: 2 },
  { w: "feed", p: "동", m: "먹이를 주다", f: ["feed"], lv: 2 },
  { w: "feedback", p: "명", m: "피드백, 의견", f: ["feedback"], lv: 2 },
  { w: "feel", p: "동", m: "느끼다", f: ["feel", "feels", "felt"], lv: 1 },
  { w: "feeling", p: "명", m: "감정, 느낌", f: ["feeling", "feelings"], lv: 1 },
  { w: "foot", p: "명", m: "발", f: ["feet"], lv: 1 },
  { w: "female", p: "형", m: "여성의, 암컷의", f: ["female"], lv: 2 },
  { w: "festival", p: "명", m: "축제", f: ["festival"], lv: 1 },
  { w: "fever", p: "명", m: "열, 발열", f: ["fever"], lv: 2 },
  { w: "few", p: "형", m: "적은, 거의 없는", f: ["fewer"], lv: 1 },
  { w: "field", p: "명", m: "들판, 분야", f: ["field"], lv: 2 },
  { w: "fight", p: "동", m: "싸우다, 싸움", f: ["fights"], lv: 1 },
  { w: "figure", p: "동", m: "알아내다, 생각하다, 숫자", f: ["figure"], lv: 2 },
  { w: "fill", p: "동", m: "채우다", f: ["fill", "filled"], lv: 1 },
  { w: "film", p: "명", m: "영화, 촬영하다", f: ["film", "filming"], lv: 2 },
  { w: "final", p: "형", m: "마지막의, 최종의", f: ["final"], lv: 2 },
  { w: "finally", p: "부", m: "마지막으로, 마침내", f: ["finally"], lv: 1 },
  { w: "find", p: "동", m: "찾다, 알게 되다", f: ["find", "finding"], lv: 1 },
  { w: "fine", p: "형", m: "좋은, 괜찮은, 벌금", f: ["fine"], lv: 1 },
  { w: "finish", p: "동", m: "끝내다", f: ["finish"], lv: 1 },
  { w: "deal with", p: "숙어", m: "~을 다루다, 처리하다", f: ["deal with"], lv: 2, ph: true, u: true },
  { w: "depend on", p: "숙어", m: "~에 의존하다, ~에 달려 있다", f: ["depend on"], lv: 2, ph: true, u: true },
  { w: "due to", p: "숙어", m: "~ 때문에", f: ["due to"], lv: 2, ph: true, u: true },
  { w: "Don't judge a book by its cover", p: "속담", m: "겉모습만 보고 판단하지 마라", f: ["don't judge a book by its cover"], lv: 2, ph: true, u: true }
);
