// 영어 기출 단어장 (파트 1)
(window.ENGLISH_VOCAB = window.ENGLISH_VOCAB || []).push(
  { w: "ability", p: "명", m: "능력", f: ["abilities"], lv: 2 },
  { w: "able", p: "형", m: "~할 수 있는", f: ["able"], lv: 1 },
  { w: "abroad", p: "부", m: "해외로, 해외에서", f: ["abroad"], lv: 2 },
  { w: "absent", p: "형", m: "결석한, 없는", f: ["absent"], lv: 2 },
  { w: "absolutely", p: "부", m: "물론이지, 전적으로", f: ["absolutely"], lv: 2 },
  { w: "absorb", p: "동", m: "흡수하다", f: ["absorb"], lv: 3 },
  { w: "accept", p: "동", m: "받아들이다, 수락하다", f: ["accept"], lv: 2 },
  { w: "accidentally", p: "부", m: "우연히, 실수로", f: ["accidentally"], lv: 2 },
  { w: "accident", p: "명", m: "사고, 우연", f: ["accidents"], lv: 2 },
  { w: "accomplishment", p: "명", m: "성취, 업적", f: ["accomplishment"], lv: 3 },
  { w: "according", p: "부", m: "~에 따라", f: ["according"], lv: 2 },
  { w: "account", p: "명", m: "계좌, 계정, 설명", f: ["account"], lv: 2 },
  { w: "accurate", p: "형", m: "정확한", f: ["accurate"], lv: 3 },
  { w: "ache", p: "명", m: "통증, 아픔", f: ["ache"], lv: 2 },
  { w: "achieve", p: "동", m: "성취하다, 이루다", f: ["achieve"], lv: 2 },
  { w: "achievement", p: "명", m: "성취, 업적", f: ["achievements"], lv: 2 },
  { w: "across", p: "전", m: "~을 가로질러, 건너편에", f: ["across"], lv: 1 },
  { w: "action", p: "명", m: "행동, 조치", f: ["action", "actions"], lv: 1 },
  { w: "active", p: "형", m: "활동적인, 적극적인", f: ["active"], lv: 2 },
  { w: "activity", p: "명", m: "활동", f: ["activities", "activity"], lv: 1 },
  { w: "actor", p: "명", m: "배우", f: ["actor", "actors"], lv: 1 },
  { w: "actually", p: "부", m: "사실은, 실제로", f: ["actually"], lv: 2 },
  { w: "add", p: "동", m: "더하다, 추가하다", f: ["add", "adding", "adds"], lv: 1 },
  { w: "addition", p: "명", m: "추가, 덧셈", f: ["addition"], lv: 2 },
  { w: "additionally", p: "부", m: "게다가, 추가로", f: ["additionally"], lv: 3 },
  { w: "address", p: "명", m: "주소, 연설", f: ["address"], lv: 1 },
  { w: "admire", p: "동", m: "존경하다, 감탄하다", f: ["admire"], lv: 2 },
  { w: "admission", p: "명", m: "입장(료), 입학", f: ["admission"], lv: 3 },
  { w: "adult", p: "명", m: "어른, 성인", f: ["adults"], lv: 1 },
  { w: "advanced", p: "형", m: "고급의, 발전된", f: ["advanced"], lv: 2 },
  { w: "advantage", p: "명", m: "장점, 이점", f: ["advantage", "advantages"], lv: 2 },
  { w: "advertisement", p: "명", m: "광고", f: ["advertisement"], lv: 2 },
  { w: "advertising", p: "명", m: "광고(업)", f: ["advertising"], lv: 2 },
  { w: "advice", p: "명", m: "조언, 충고", f: ["advice"], lv: 2 },
  { w: "afraid", p: "형", m: "두려워하는, 걱정하는", f: ["afraid"], lv: 1 },
  { w: "afternoon", p: "명", m: "오후", f: ["afternoon"], lv: 1 },
  { w: "afterwards", p: "부", m: "나중에, 그 후에", f: ["afterwards"], lv: 2 },
  { w: "again", p: "부", m: "다시, 또", f: ["again"], lv: 1 },
  { w: "against", p: "전", m: "~에 반대하여, ~에 맞서", f: ["against"], lv: 2 },
  { w: "age", p: "명", m: "나이, 시대", f: ["age", "ages"], lv: 1 },
  { w: "aged", p: "형", m: "~세의, 나이 든", f: ["aged"], lv: 2 },
  { w: "aging", p: "명", m: "노화, 고령화", f: ["aging"], lv: 3 },
  { w: "ago", p: "부", m: "~ 전에", f: ["ago"], lv: 1 },
  { w: "agree", p: "동", m: "동의하다", f: ["agree"], lv: 1 },
  { w: "ah", p: "감", m: "아", f: ["ah"], lv: 1 },
  { w: "AI", p: "명", m: "인공지능", f: ["ai"], lv: 2 },
  { w: "air", p: "명", m: "공기, 공중", f: ["air"], lv: 1 },
  { w: "airline", p: "명", m: "항공사", f: ["airlines"], lv: 2 },
  { w: "airplane", p: "명", m: "비행기", f: ["airplanes"], lv: 1 },
  { w: "alert", p: "명", m: "경보, 알림", f: ["alert"], lv: 3 },
  { w: "allow", p: "동", m: "허락하다, 허용하다", f: ["allowed", "allowing"], lv: 2 },
  { w: "almost", p: "부", m: "거의", f: ["almost"], lv: 1 },
  { w: "alone", p: "부", m: "혼자, 홀로", f: ["alone"], lv: 1 },
  { w: "along", p: "전", m: "~을 따라", f: ["along"], lv: 1 },
  { w: "alphabetical", p: "형", m: "알파벳순의", f: ["alphabetical"], lv: 3 },
  { w: "already", p: "부", m: "이미, 벌써", f: ["already"], lv: 1 },
  { w: "alternative", p: "명", m: "대안", f: ["alternatives"], lv: 3 },
  { w: "although", p: "접", m: "비록 ~이지만", f: ["although"], lv: 2 },
  { w: "always", p: "부", m: "항상, 언제나", f: ["always"], lv: 1 },
  { w: "amazed", p: "형", m: "놀란", f: ["amazed"], lv: 2 },
  { w: "amazing", p: "형", m: "놀라운", f: ["amazing"], lv: 1 },
  { w: "amount", p: "명", m: "양, 금액", f: ["amount", "amounts"], lv: 2 },
  { w: "ancestor", p: "명", m: "조상", f: ["ancestors"], lv: 3 },
  { w: "ancient", p: "형", m: "고대의, 아주 오래된", f: ["ancient"], lv: 2 },
  { w: "anger", p: "명", m: "화, 분노", f: ["anger"], lv: 2 },
  { w: "angry", p: "형", m: "화난", f: ["angry"], lv: 1 },
  { w: "animal", p: "명", m: "동물", f: ["animal", "animals"], lv: 1 },
  { w: "announce", p: "동", m: "발표하다, 알리다", f: ["announce", "announced"], lv: 2 },
  { w: "announcement", p: "명", m: "발표, 안내 방송", f: ["announcement", "announcements"], lv: 2 },
  { w: "answer", p: "명", m: "대답, 답", f: ["answer", "answers"], lv: 1 },
  { w: "anxiety", p: "명", m: "불안, 걱정", f: ["anxiety"], lv: 3 },
  { w: "anxious", p: "형", m: "불안한, 걱정하는", f: ["anxious"], lv: 2 },
  { w: "anymore", p: "부", m: "더 이상", f: ["anymore"], lv: 1 },
  { w: "anyone", p: "대", m: "누구든지, 아무도", f: ["anyone"], lv: 1 },
  { w: "anything", p: "대", m: "무엇이든, 아무것도", f: ["anything"], lv: 1 },
  { w: "anytime", p: "부", m: "언제든지", f: ["anytime"], lv: 1 },
  { w: "anywhere", p: "부", m: "어디든지, 아무 데도", f: ["anywhere"], lv: 1 },
  { w: "apartment", p: "명", m: "아파트", f: ["apartment"], lv: 1 },
  { w: "apologize", p: "동", m: "사과하다", f: ["apologize", "apologized"], lv: 2 },
  { w: "appear", p: "동", m: "나타나다, ~처럼 보이다", f: ["appear"], lv: 2 },
  { w: "appearance", p: "명", m: "외모, 출현", f: ["appearance"], lv: 2 },
  { w: "apple", p: "명", m: "사과", f: ["apple"], lv: 1 },
  { w: "application", p: "명", m: "지원(서), 앱", f: ["application"], lv: 2 },
  { w: "apply", p: "동", m: "지원하다, 적용하다", f: ["apply"], lv: 2 },
  { w: "appreciate", p: "동", m: "감사하다, 진가를 알다", f: ["appreciated"], lv: 2 },
  { w: "appropriate", p: "형", m: "적절한", f: ["appropriate"], lv: 3 },
  { w: "April", p: "명", m: "4월", f: ["april"], lv: 1 },
  { w: "aquarium", p: "명", m: "수족관", f: ["aquarium"], lv: 2 },
  { w: "architecture", p: "명", m: "건축(학), 건축 양식", f: ["architecture"], lv: 3 },
  { w: "area", p: "명", m: "지역, 구역", f: ["area", "areas"], lv: 1 },
  { w: "argue", p: "동", m: "말다툼하다, 주장하다", f: ["argue"], lv: 2 },
  { w: "arise", p: "동", m: "생기다, 발생하다", f: ["arising"], lv: 3 },
  { w: "arm", p: "명", m: "팔", f: ["arms"], lv: 1 },
  { w: "around", p: "전", m: "~ 주위에, 약, 여기저기", f: ["around"], lv: 1 },
  { w: "arrange", p: "동", m: "정리하다, 배열하다", f: ["arranging"], lv: 2 },
  { w: "arrest", p: "동", m: "체포하다", f: ["arresting"], lv: 3 },
  { w: "arrival", p: "명", m: "도착", f: ["arrival"], lv: 2 },
  { w: "arrive", p: "동", m: "도착하다", f: ["arrive", "arrived"], lv: 1 },
  { w: "arrow", p: "명", m: "화살, 화살표", f: ["arrow"], lv: 2 },
  { w: "art", p: "명", m: "미술, 예술", f: ["art", "arts"], lv: 1 },
  { w: "article", p: "명", m: "기사, 글", f: ["article", "articles"], lv: 2 },
  { w: "artificial", p: "형", m: "인공의, 인조의", f: ["artificial"], lv: 3 },
  { w: "artist", p: "명", m: "예술가, 화가", f: ["artist", "artists"], lv: 1 },
  { w: "artwork", p: "명", m: "미술품, 삽화", f: ["artwork"], lv: 2 },
  { w: "Asian", p: "형", m: "아시아의, 아시아인", f: ["asian", "asians"], lv: 2 },
  { w: "ask", p: "동", m: "묻다, 요청하다", f: ["ask", "asked", "asking"], lv: 1 },
  { w: "asleep", p: "형", m: "잠든", f: ["asleep"], lv: 2 },
  { w: "astronaut", p: "명", m: "우주비행사", f: ["astronauts"], lv: 2 },
  { w: "eat", p: "동", m: "먹다", f: ["ate"], lv: 1 },
  { w: "atomic", p: "형", m: "원자의, 원자력의", f: ["atomic"], lv: 3 },
  { w: "attach", p: "동", m: "첨부하다, 붙이다", f: ["attaching"], lv: 2 },
  { w: "attention", p: "명", m: "주의, 주목", f: ["attention"], lv: 2 },
  { w: "attract", p: "동", m: "끌어들이다, 매혹하다", f: ["attract", "attracted"], lv: 2 },
  { w: "audience", p: "명", m: "관객, 청중", f: ["audience"], lv: 2 },
  { w: "auditorium", p: "명", m: "강당", f: ["auditorium"], lv: 3 },
  { w: "August", p: "명", m: "8월", f: ["august"], lv: 1 },
  { w: "author", p: "명", m: "작가, 저자", f: ["author"], lv: 2 },
  { w: "autumn", p: "명", m: "가을", f: ["autumn"], lv: 1 },
  { w: "available", p: "형", m: "이용 가능한, 시간이 있는", f: ["available"], lv: 2 },
  { w: "average", p: "형", m: "평균의, 보통의", f: ["average"], lv: 2 },
  { w: "avoid", p: "동", m: "피하다", f: ["avoid", "avoided"], lv: 2 },
  { w: "awake", p: "형", m: "깨어 있는", f: ["awake"], lv: 2 },
  { w: "aware", p: "형", m: "알고 있는, 인식하는", f: ["aware"], lv: 2 },
  { w: "away", p: "부", m: "떨어져, 멀리", f: ["away"], lv: 1 },
  { w: "awesome", p: "형", m: "굉장한, 멋진", f: ["awesome"], lv: 2 },
  { w: "baby", p: "명", m: "아기", f: ["babies", "baby"], lv: 1 },
  { w: "back", p: "부", m: "뒤로, 다시, 돌아와", f: ["back"], lv: 1 },
  { w: "background", p: "명", m: "배경, 경력", f: ["backgrounds"], lv: 2 },
  { w: "backpack", p: "명", m: "배낭, 책가방", f: ["backpack"], lv: 1 },
  { w: "bad", p: "형", m: "나쁜, 해로운", f: ["bad"], lv: 1 },
  { w: "badminton", p: "명", m: "배드민턴", f: ["badminton"], lv: 1 },
  { w: "bag", p: "명", m: "가방, 봉지", f: ["bag", "bags"], lv: 1 },
  { w: "bake", p: "동", m: "(빵 등을) 굽다", f: ["baked", "baking"], lv: 1 },
  { w: "baker", p: "명", m: "제빵사", f: ["baker"], lv: 1 },
  { w: "bakery", p: "명", m: "빵집, 제과점", f: ["bakeries", "bakery"], lv: 1 },
  { w: "balance", p: "명", m: "균형", f: ["balance"], lv: 2, u: true },
  { w: "ball", p: "명", m: "공", f: ["ball", "balls"], lv: 1 },
  { w: "balloon", p: "명", m: "풍선", f: ["balloon"], lv: 1 },
  { w: "band", p: "명", m: "밴드, 악단", f: ["band"], lv: 1 },
  { w: "bank", p: "명", m: "은행", f: ["bank"], lv: 1 },
  { w: "banker", p: "명", m: "은행원", f: ["banker"], lv: 2 },
  { w: "baobab", p: "명", m: "바오밥나무", f: ["baobob", "baobobs"], lv: 3 },
  { w: "barber", p: "명", m: "이발사", f: ["barber"], lv: 2 },
  { w: "baseball", p: "명", m: "야구", f: ["baseball"], lv: 1 },
  { w: "based", p: "형", m: "~에 근거한, ~에 기반을 둔", f: ["based"], lv: 2 },
  { w: "basis", p: "명", m: "기초, 기준", f: ["basis"], lv: 3 },
  { w: "basketball", p: "명", m: "농구", f: ["basketball"], lv: 1 },
  { w: "battery", p: "명", m: "배터리, 건전지", f: ["battery"], lv: 2 },
  { w: "beach", p: "명", m: "해변", f: ["beach"], lv: 1 },
  { w: "bean", p: "명", m: "콩", f: ["beans"], lv: 1 },
  { w: "beat", p: "동", m: "이기다, 두드리다", f: ["beat"], lv: 2 },
  { w: "beautiful", p: "형", m: "아름다운", f: ["beautiful"], lv: 1 },
  { w: "become", p: "동", m: "~이 되다", f: ["became", "become", "becomes", "becoming"], lv: 1 },
  { w: "because", p: "접", m: "~ 때문에", f: ["because"], lv: 1 },
  { w: "bed", p: "명", m: "침대", f: ["bed"], lv: 1 },
  { w: "bee", p: "명", m: "벌", f: ["bees"], lv: 1 },
  { w: "begin", p: "동", m: "시작하다", f: ["began", "begin", "beginning", "begins", "begun"], lv: 1 },
  { w: "beginner", p: "명", m: "초보자", f: ["beginners"], lv: 2 },
  { w: "behavior", p: "명", m: "행동, 태도", f: ["behavior"], lv: 2, u: true },
  { w: "behind", p: "전", m: "~ 뒤에", f: ["behind"], lv: 1 },
  { w: "being", p: "명", m: "존재, 생명체", f: ["beings"], lv: 3 },
  { w: "believe", p: "동", m: "믿다, 생각하다", f: ["believe", "believed", "believes", "believing"], lv: 1 },
  { w: "belongings", p: "명", m: "소지품", f: ["belongings"], lv: 3 },
  { w: "beneficial", p: "형", m: "유익한, 이로운", f: ["beneficial"], lv: 3 },
  { w: "benefit", p: "명", m: "이익, 혜택", f: ["benefit", "benefits"], lv: 2, u: true },
  { w: "besides", p: "부", m: "게다가, ~ 외에", f: ["besides"], lv: 2, u: true },
  { w: "good", p: "형", m: "좋은, 잘하는", f: ["best", "better"], lv: 1 },
  { w: "bicycle", p: "명", m: "자전거", f: ["bicycle", "bicycles"], lv: 1 },
  { w: "big", p: "형", m: "큰", f: ["big", "bigger", "biggest"], lv: 1 },
  { w: "bike", p: "명", m: "자전거", f: ["bikes"], lv: 1 },
  { w: "biking", p: "명", m: "자전거 타기", f: ["biking"], lv: 1 },
  { w: "bill", p: "명", m: "청구서, 지폐", f: ["bills"], lv: 2 },
  { w: "biology", p: "명", m: "생물학", f: ["biology"], lv: 2 },
  { w: "bird", p: "명", m: "새", f: ["birds"], lv: 1 },
  { w: "birth", p: "명", m: "출생, 탄생", f: ["birth"], lv: 2 },
  { w: "birthday", p: "명", m: "생일", f: ["birthday", "birthdays"], lv: 1 },
  { w: "bit", p: "명", m: "조금, 약간", f: ["bit"], lv: 1 },
  { w: "bitter", p: "형", m: "(맛이) 쓴, 쓰라린", f: ["bitter"], lv: 2, u: true },
  { w: "black", p: "형", m: "검은", f: ["black"], lv: 1 },
  { w: "blackboard", p: "명", m: "칠판", f: ["blackboard"], lv: 1 },
  { w: "blame", p: "동", m: "탓하다, 비난하다", f: ["blame"], lv: 2 },
  { w: "block", p: "명", m: "블록, (도로의) 구역", f: ["blocks"], lv: 2 },
  { w: "blood", p: "명", m: "피, 혈액", f: ["blood"], lv: 1 },
  { w: "blue", p: "형", m: "파란", f: ["blue"], lv: 1 },
  { w: "boarding", p: "명", m: "탑승", f: ["boarding"], lv: 2 },
  { w: "body", p: "명", m: "몸, 신체", f: ["bodies", "body"], lv: 1 },
  { w: "bomb", p: "명", m: "폭탄", f: ["bomb"], lv: 2 },
  { w: "book", p: "명", m: "책; 예약하다", f: ["book", "booked", "books"], lv: 1 },
  { w: "bookstore", p: "명", m: "서점", f: ["bookstore"], lv: 1 },
  { w: "booth", p: "명", m: "부스, 칸막이 공간", f: ["booth", "booths"], lv: 2 },
  { w: "bored", p: "형", m: "지루해하는", f: ["bored"], lv: 1 },
  { w: "boring", p: "형", m: "지루한", f: ["boring"], lv: 1 },
  { w: "born", p: "형", m: "태어난", f: ["born"], lv: 1 },
  { w: "borrow", p: "동", m: "빌리다", f: ["borrow", "borrowed"], lv: 1 },
  { w: "bottom", p: "명", m: "맨 아래, 바닥", f: ["bottom"], lv: 2 },
  { w: "buy", p: "동", m: "사다, 구입하다", f: ["bought", "buy", "buying"], lv: 1 },
  { w: "brain", p: "명", m: "뇌, 두뇌", f: ["brain"], lv: 2 },
  { w: "branch", p: "명", m: "나뭇가지, 지점", f: ["branches"], lv: 2 },
  { w: "bread", p: "명", m: "빵", f: ["bread"], lv: 1 },
  { w: "break", p: "명", m: "휴식; 깨다, 부수다", f: ["break", "broke"], lv: 1 },
  { w: "breakdancing", p: "명", m: "브레이크댄스", f: ["breakdancing"], lv: 2 },
  { w: "breakfast", p: "명", m: "아침 식사", f: ["breakfast"], lv: 1 },
  { w: "breath", p: "명", m: "숨, 호흡", f: ["breath"], lv: 2 },
  { w: "breathe", p: "동", m: "숨 쉬다, 호흡하다", f: ["breathe"], lv: 2 },
  { w: "breed", p: "명", m: "품종", f: ["breed"], lv: 3 },
  { w: "brief", p: "형", m: "짧은, 간단한", f: ["brief"], lv: 2 },
  { w: "bright", p: "형", m: "밝은, 똑똑한", f: ["bright"], lv: 1, u: true },
  { w: "bring", p: "동", m: "가져오다, 데려오다", f: ["bring", "bringing", "brought"], lv: 1 },
  { w: "British", p: "형", m: "영국의, 영국인", f: ["british"], lv: 2 },
  { w: "budget", p: "명", m: "예산", f: ["budget"], lv: 3 },
  { w: "build", p: "동", m: "짓다, 만들다", f: ["build", "builds", "built"], lv: 1 },
  { w: "building", p: "명", m: "건물", f: ["building", "buildings"], lv: 1 },
  { w: "bungee", p: "명", m: "번지(점프)", f: ["bungee"], lv: 3 },
  { w: "burger", p: "명", m: "버거, 햄버거", f: ["burger", "burgers"], lv: 1 },
  { w: "burn", p: "동", m: "태우다, 데다; 화상", f: ["burn", "burning", "burns"], lv: 2 },
  { w: "bus", p: "명", m: "버스", f: ["bus"], lv: 1, u: true },
  { w: "business", p: "명", m: "사업, 일, 업체", f: ["business"], lv: 2 },
  { w: "busy", p: "형", m: "바쁜, 붐비는", f: ["busy"], lv: 1 },
  { w: "button", p: "명", m: "버튼, 단추", f: ["button"], lv: 1 },
  { w: "cable", p: "명", m: "케이블, 전선", f: ["cable", "cables"], lv: 2 },
  { w: "caffeine", p: "명", m: "카페인", f: ["caffeine"], lv: 2 },
  { w: "cake", p: "명", m: "케이크", f: ["cake", "cakes"], lv: 1 },
  { w: "call", p: "동", m: "부르다, 전화하다", f: ["call", "called"], lv: 1 },
  { w: "calm", p: "형", m: "침착한, 차분한", f: ["calm"], lv: 2 },
  { w: "calming", p: "형", m: "진정시키는", f: ["calming"], lv: 2 },
  { w: "calmly", p: "부", m: "침착하게, 차분하게", f: ["calmly"], lv: 2 },
  { w: "calorie", p: "명", m: "칼로리, 열량", f: ["calories"], lv: 2 },
  { w: "come", p: "동", m: "오다", f: ["came"], lv: 1 },
  { w: "camel", p: "명", m: "낙타", f: ["camel", "camels"], lv: 2 },
  { w: "camp", p: "명", m: "캠프, 야영지", f: ["camp"], lv: 1 },
  { w: "campaign", p: "명", m: "캠페인, (조직적) 운동", f: ["campaign"], lv: 2 },
  { w: "camping", p: "명", m: "캠핑, 야영", f: ["camping"], lv: 1 },
  { w: "cancel", p: "동", m: "취소하다", f: ["cancel", "canceled"], lv: 2 },
  { w: "cancer", p: "명", m: "암", f: ["cancer"], lv: 2 },
  { w: "cannot", p: "동", m: "~할 수 없다", f: ["cannot"], lv: 1 },
  { w: "can", p: "명", m: "캔, 깡통", f: ["cans"], lv: 1 },
  { w: "cap", p: "명", m: "모자, 뚜껑", f: ["cap", "caps"], lv: 1 },
  { w: "car", p: "명", m: "자동차", f: ["car", "cars"], lv: 1 },
  { w: "carbon", p: "명", m: "탄소", f: ["carbon"], lv: 3 },
  { w: "card", p: "명", m: "카드", f: ["card", "cards"], lv: 1 },
  { w: "care", p: "명", m: "돌봄, 주의; 신경 쓰다", f: ["care"], lv: 1 },
  { w: "career", p: "명", m: "직업, 경력", f: ["career"], lv: 2 },
  { w: "careful", p: "형", m: "조심하는, 신중한", f: ["careful"], lv: 1 },
  { w: "carefully", p: "부", m: "조심스럽게, 주의 깊게", f: ["carefully"], lv: 1 },
  { w: "careless", p: "형", m: "부주의한", f: ["careless"], lv: 2 },
  { w: "carry", p: "동", m: "나르다, 가지고 다니다", f: ["carry"], lv: 1 },
  { w: "case", p: "명", m: "경우, 사례, 상자", f: ["case", "cases"], lv: 2 },
  { w: "cash", p: "명", m: "현금", f: ["cash"], lv: 1 },
  { w: "casual", p: "형", m: "평상시의, 격식 없는", f: ["casual"], lv: 2 },
  { w: "cat", p: "명", m: "고양이", f: ["cat", "cats"], lv: 1 },
  { w: "catch", p: "동", m: "잡다, (병에) 걸리다", f: ["catch"], lv: 1 },
  { w: "cause", p: "동", m: "일으키다; 원인", f: ["cause", "caused", "causes"], lv: 2 },
  { w: "cautious", p: "형", m: "조심스러운, 신중한", f: ["cautious"], lv: 3 },
  { w: "cave", p: "명", m: "동굴", f: ["cave", "caves"], lv: 2 },
  { w: "CD", p: "명", m: "시디(CD)", f: ["cd", "cds"], lv: 1 },
  { w: "celebrate", p: "동", m: "축하하다, 기념하다", f: ["celebrate", "celebrated", "celebrates"], lv: 2 },
  { w: "cellphone", p: "명", m: "휴대전화", f: ["cellphone"], lv: 1 },
  { w: "center", p: "명", m: "센터, 중심", f: ["center"], lv: 1 },
  { w: "central", p: "형", m: "중앙의, 중심의", f: ["central"], lv: 2 },
  { w: "chair", p: "명", m: "의자", f: ["chair"], lv: 1 },
  { w: "challenging", p: "형", m: "도전적인, 힘든", f: ["challenging"], lv: 3 },
  { w: "chance", p: "명", m: "기회, 가능성", f: ["chance"], lv: 1 },
  { w: "change", p: "동", m: "바꾸다, 변하다; 변화", f: ["change", "changes"], lv: 1 },
  { w: "charge", p: "명", m: "요금, 책임", f: ["charge"], lv: 2 },
  { w: "charity", p: "명", m: "자선 (단체)", f: ["charity"], lv: 3 },
  { w: "cheap", p: "형", m: "값싼", f: ["cheap"], lv: 1 },
  { w: "check", p: "동", m: "확인하다, 점검하다", f: ["check"], lv: 1 },
  { w: "cheese", p: "명", m: "치즈", f: ["cheese"], lv: 1 },
  { w: "chef", p: "명", m: "요리사", f: ["chef"], lv: 2 },
  { w: "chemical", p: "명", m: "화학 물질", f: ["chemicals"], lv: 3 },
  { w: "child", p: "명", m: "아이, 어린이", f: ["child", "children"], lv: 1 },
  { w: "chimpanzee", p: "명", m: "침팬지", f: ["chimpanzee"], lv: 2 },
  { w: "Chinese", p: "형", m: "중국의, 중국어", f: ["chinese"], lv: 1 },
  { w: "chocolate", p: "명", m: "초콜릿", f: ["chocolate"], lv: 1 },
  { w: "choice", p: "명", m: "선택", f: ["choice", "choices"], lv: 2 },
  { w: "choose", p: "동", m: "고르다, 선택하다", f: ["choose", "choosing", "chose", "chosen"], lv: 1 },
  { w: "church", p: "명", m: "교회", f: ["church"], lv: 1 },
  { w: "city", p: "명", m: "도시", f: ["cities", "city"], lv: 1 },
  { w: "class", p: "명", m: "수업, 학급", f: ["class", "classes"], lv: 1 },
  { w: "classmate", p: "명", m: "반 친구", f: ["classmates"], lv: 1 },
  { w: "classroom", p: "명", m: "교실", f: ["classroom"], lv: 1 },
  { w: "clay", p: "명", m: "점토, 찰흙", f: ["clay"], lv: 2 },
  { w: "clean", p: "동", m: "청소하다; 깨끗한", f: ["clean", "cleaned", "cleaning"], lv: 1 },
  { w: "clear", p: "형", m: "분명한, 맑은", f: ["clear"], lv: 2 },
  { w: "click", p: "동", m: "클릭하다", f: ["click"], lv: 1 },
  { w: "cliff", p: "명", m: "절벽", f: ["cliffs"], lv: 3 },
  { w: "climate", p: "명", m: "기후", f: ["climate"], lv: 2 },
  { w: "climb", p: "동", m: "오르다, 등반하다", f: ["climb"], lv: 1 },
  { w: "close", p: "동", m: "닫다; 가까운", f: ["close", "closed"], lv: 1 },
  { w: "cloth", p: "명", m: "천, 옷감", f: ["cloth"], lv: 2 },
  { w: "clothes", p: "명", m: "옷, 의복", f: ["clothes"], lv: 1 },
  { w: "club", p: "명", m: "동아리, 클럽", f: ["club"], lv: 1 },
  { w: "according to", p: "숙어", m: "~에 따르면", f: ["according to"], lv: 2, ph: true, u: true },
  { w: "at last", p: "숙어", m: "마침내, 드디어", f: ["at last"], lv: 2, ph: true, u: true },
  { w: "after all", p: "숙어", m: "결국, 어쨌든", f: ["after all"], lv: 2, ph: true, u: true },
  { w: "as a result", p: "숙어", m: "결과적으로", f: ["as a result"], lv: 2, ph: true, u: true },
  { w: "be aware of", p: "숙어", m: "~을 알고 있다", f: ["be aware of", "are aware of"], lv: 2, ph: true, u: true },
  { w: "A journey of a thousand miles starts with a single step", p: "속담", m: "천 리 길도 한 걸음부터", f: ["a journey of a thousand miles starts with a single step"], lv: 2, ph: true, u: true },
  { w: "A friend in need is a friend indeed", p: "속담", m: "어려울 때 친구가 진정한 친구다", f: ["a friend in need is a friend indeed"], lv: 2, ph: true, u: true },
  { w: "Better late than never", p: "속담", m: "늦더라도 안 하는 것보다 낫다", f: ["better late than never"], lv: 2, ph: true, u: true }
);
