// 영어 기출 단어장 (파트 4)
(window.ENGLISH_VOCAB = window.ENGLISH_VOCAB || []).push(
  { w: "leg", p: "명", m: "다리", f: ["leg"], lv: 1 },
  { w: "length", p: "명", m: "길이", f: ["lengths"], lv: 2 },
  { w: "lesson", p: "명", m: "수업, 교훈", f: ["lesson", "lessons"], lv: 1 },
  { w: "let", p: "동", m: "~하게 하다, 허락하다", f: ["let"], lv: 1 },
  { w: "letter", p: "명", m: "편지, 글자", f: ["letter"], lv: 1 },
  { w: "level", p: "명", m: "수준, 정도", f: ["levels"], lv: 2 },
  { w: "library", p: "명", m: "도서관", f: ["library"], lv: 1 },
  { w: "life", p: "명", m: "삶, 생명, 생활", f: ["life", "lives"], lv: 1 },
  { w: "lifeguard", p: "명", m: "인명 구조원", f: ["lifeguard"], lv: 2 },
  { w: "light", p: "명", m: "빛, 전등, 가벼운", f: ["light", "lights"], lv: 1 },
  { w: "lightweight", p: "형", m: "가벼운, 경량의", f: ["lightweight"], lv: 3 },
  { w: "like", p: "동", m: "좋아하다, ~와 같은", f: ["like", "liked", "likes"], lv: 1 },
  { w: "likewise", p: "부", m: "마찬가지로", f: ["likewise"], lv: 3 },
  { w: "limit", p: "명", m: "제한, 한계", f: ["limit"], lv: 2 },
  { w: "line", p: "명", m: "줄, 선", f: ["line", "lines"], lv: 1 },
  { w: "link", p: "명", m: "연결, 관련", f: ["links"], lv: 2 },
  { w: "list", p: "명", m: "목록, 명단", f: ["list"], lv: 1 },
  { w: "listen", p: "동", m: "듣다, 귀 기울이다", f: ["listen", "listening"], lv: 1 },
  { w: "listener", p: "명", m: "듣는 사람, 청취자", f: ["listener"], lv: 2 },
  { w: "live", p: "동", m: "살다, 생활하다", f: ["live", "lived", "living"], lv: 1 },
  { w: "lobby", p: "명", m: "로비, 현관", f: ["lobby"], lv: 2 },
  { w: "local", p: "형", m: "지역의, 현지의", f: ["local"], lv: 2 },
  { w: "locate", p: "동", m: "(~에) 위치하다, 찾아내다", f: ["located"], lv: 2 },
  { w: "location", p: "명", m: "위치, 장소", f: ["location", "locations"], lv: 2 },
  { w: "locker", p: "명", m: "사물함", f: ["lockers"], lv: 2 },
  { w: "logical", p: "형", m: "논리적인", f: ["logical"], lv: 2 },
  { w: "loneliness", p: "명", m: "외로움", f: ["loneliness"], lv: 3 },
  { w: "lonely", p: "형", m: "외로운", f: ["lonely"], lv: 1 },
  { w: "long", p: "형", m: "긴, 오래", f: ["long", "longer"], lv: 1 },
  { w: "look", p: "동", m: "보다, ~해 보이다", f: ["look", "looked", "looking", "looks"], lv: 1 },
  { w: "loose", p: "형", m: "헐렁한, 느슨한", f: ["loose"], lv: 2 },
  { w: "lose", p: "동", m: "잃다, 지다, (살을) 빼다", f: ["lose", "lost"], lv: 1 },
  { w: "lot", p: "명", m: "많음(a lot of), 많이", f: ["lot", "lots"], lv: 1 },
  { w: "lotion", p: "명", m: "로션", f: ["lotion"], lv: 2 },
  { w: "loud", p: "형", m: "시끄러운, 큰 소리의", f: ["loud"], lv: 1 },
  { w: "love", p: "동", m: "사랑하다, 매우 좋아하다", f: ["love"], lv: 1 },
  { w: "low", p: "형", m: "낮은", f: ["low", "lower"], lv: 1 },
  { w: "lower", p: "동", m: "낮추다, 내리다", f: ["lowers"], lv: 2 },
  { w: "luckily", p: "부", m: "다행히, 운 좋게", f: ["luckily"], lv: 2 },
  { w: "lucky", p: "형", m: "운 좋은", f: ["lucky"], lv: 1 },
  { w: "luggage", p: "명", m: "짐, 수하물", f: ["luggage"], lv: 2 },
  { w: "lunch", p: "명", m: "점심", f: ["lunch"], lv: 1 },
  { w: "lunchtime", p: "명", m: "점심시간", f: ["lunchtime"], lv: 1 },
  { w: "machine", p: "명", m: "기계", f: ["machine"], lv: 1 },
  { w: "magic", p: "명", m: "마술, 마법", f: ["magic"], lv: 1 },
  { w: "mail", p: "명", m: "우편, 우편물", f: ["mail"], lv: 1 },
  { w: "main", p: "형", m: "주된, 주요한", f: ["main"], lv: 2 },
  { w: "maintain", p: "동", m: "유지하다", f: ["maintain"], lv: 2 },
  { w: "major", p: "형", m: "주요한, 전공(하다)", f: ["major", "majoring"], lv: 2 },
  { w: "make", p: "동", m: "만들다, ~하게 하다", f: ["make", "made", "makes", "making"], lv: 1 },
  { w: "man", p: "명", m: "남자, 사람", f: ["man"], lv: 1 },
  { w: "manage", p: "동", m: "관리하다, 해내다", f: ["manage", "managing"], lv: 2 },
  { w: "management", p: "명", m: "관리, 경영", f: ["management"], lv: 2 },
  { w: "manager", p: "명", m: "관리자, 매니저", f: ["manager"], lv: 2 },
  { w: "mango", p: "명", m: "망고", f: ["mango", "mangoes"], lv: 1 },
  { w: "map", p: "명", m: "지도", f: ["maps"], lv: 1 },
  { w: "marathon", p: "명", m: "마라톤", f: ["marathon", "marathons"], lv: 2 },
  { w: "March", p: "명", m: "3월", f: ["march"], lv: 1 },
  { w: "marine", p: "형", m: "바다의, 해양의", f: ["marine"], lv: 3 },
  { w: "market", p: "명", m: "시장", f: ["market"], lv: 1 },
  { w: "Mars", p: "명", m: "화성", f: ["mars"], lv: 2 },
  { w: "mask", p: "명", m: "마스크, 가면", f: ["mask", "masks"], lv: 1 },
  { w: "match", p: "동", m: "어울리다, 일치하다, 경기", f: ["match", "matched"], lv: 2 },
  { w: "material", p: "명", m: "재료, 물질, 자료", f: ["material", "materials"], lv: 2 },
  { w: "math", p: "명", m: "수학", f: ["math"], lv: 1 },
  { w: "matter", p: "명", m: "문제, 일, 중요하다", f: ["matter"], lv: 2 },
  { w: "maybe", p: "부", m: "아마, 어쩌면", f: ["maybe"], lv: 1 },
  { w: "meal", p: "명", m: "식사, 끼니", f: ["meal"], lv: 1 },
  { w: "mean", p: "동", m: "의미하다, 의도하다", f: ["mean", "means", "meant"], lv: 1 },
  { w: "meaning", p: "명", m: "의미, 뜻", f: ["meaning", "meanings"], lv: 2 },
  { w: "measure", p: "동", m: "측정하다, 재다", f: ["measure"], lv: 2 },
  { w: "mechanic", p: "명", m: "정비사, 기계공", f: ["mechanic"], lv: 3 },
  { w: "medical", p: "형", m: "의학의, 의료의", f: ["medical"], lv: 2 },
  { w: "medicine", p: "명", m: "약, 의학", f: ["medicine"], lv: 2 },
  { w: "medium", p: "형", m: "중간의, 보통의", f: ["medium"], lv: 2 },
  { w: "meet", p: "동", m: "만나다, 충족시키다", f: ["meet", "meets", "met"], lv: 1 },
  { w: "meeting", p: "명", m: "회의, 모임", f: ["meeting"], lv: 1 },
  { w: "melt", p: "동", m: "녹다, 녹이다", f: ["melting"], lv: 2 },
  { w: "member", p: "명", m: "회원, 구성원", f: ["members"], lv: 1 },
  { w: "memorize", p: "동", m: "암기하다, 외우다", f: ["memorize", "memorizing"], lv: 2 },
  { w: "mental", p: "형", m: "정신의, 마음의", f: ["mental"], lv: 2 },
  { w: "menu", p: "명", m: "메뉴, 차림표", f: ["menu"], lv: 1 },
  { w: "message", p: "명", m: "메시지, 전갈", f: ["message"], lv: 1 },
  { w: "metal", p: "명", m: "금속", f: ["metal"], lv: 2 },
  { w: "method", p: "명", m: "방법", f: ["method"], lv: 2 },
  { w: "middle", p: "명", m: "중간, 가운데", f: ["middle"], lv: 1 },
  { w: "midnight", p: "명", m: "자정, 한밤중", f: ["midnight"], lv: 2 },
  { w: "mile", p: "명", m: "마일(약 1.6km)", f: ["miles"], lv: 2 },
  { w: "milk", p: "명", m: "우유", f: ["milk"], lv: 1 },
  { w: "million", p: "명", m: "백만", f: ["million"], lv: 1 },
  { w: "mind", p: "명", m: "마음, 정신, 꺼리다", f: ["mind"], lv: 1 },
  { w: "minute", p: "명", m: "(시간의) 분, 잠깐", f: ["minute", "minutes"], lv: 1 },
  { w: "miss", p: "동", m: "그리워하다, 놓치다", f: ["miss", "missed"], lv: 1 },
  { w: "mistake", p: "명", m: "실수, 잘못", f: ["mistake", "mistakes"], lv: 1 },
  { w: "misunderstand", p: "동", m: "오해하다", f: ["misunderstood"], lv: 3 },
  { w: "mix", p: "동", m: "섞다, 섞이다", f: ["mix", "mixed"], lv: 1 },
  { w: "model", p: "명", m: "모형, 모델, 본보기", f: ["model", "models"], lv: 1 },
  { w: "modern", p: "형", m: "현대의, 현대적인", f: ["modern"], lv: 2 },
  { w: "mom", p: "명", m: "엄마", f: ["mom"], lv: 1 },
  { w: "moment", p: "명", m: "순간, 잠시", f: ["moment"], lv: 1 },
  { w: "Monday", p: "명", m: "월요일", f: ["monday", "mondays"], lv: 1 },
  { w: "money", p: "명", m: "돈", f: ["money"], lv: 1 },
  { w: "monitor", p: "동", m: "감시하다, 관찰하다, 모니터", f: ["monitor"], lv: 2 },
  { w: "month", p: "명", m: "달, 월", f: ["month", "months"], lv: 1 },
  { w: "mood", p: "명", m: "기분, 분위기", f: ["moods"], lv: 2 },
  { w: "moonlight", p: "명", m: "달빛", f: ["moonlight"], lv: 2 },
  { w: "moreover", p: "부", m: "게다가, 더욱이", f: ["moreover"], lv: 2 },
  { w: "morning", p: "명", m: "아침, 오전", f: ["morning"], lv: 1 },
  { w: "mother", p: "명", m: "어머니", f: ["mother"], lv: 1 },
  { w: "motivate", p: "동", m: "동기를 부여하다", f: ["motivate"], lv: 3 },
  { w: "mountain", p: "명", m: "산", f: ["mountain", "mountains"], lv: 1 },
  { w: "move", p: "동", m: "움직이다, 이사하다", f: ["move", "moved", "moves", "moving"], lv: 1 },
  { w: "movie", p: "명", m: "영화", f: ["movie", "movies"], lv: 1 },
  { w: "mud", p: "명", m: "진흙", f: ["mud"], lv: 2 },
  { w: "mug", p: "명", m: "머그잔", f: ["mug"], lv: 2 },
  { w: "multicultural", p: "형", m: "다문화의", f: ["multicultural"], lv: 3 },
  { w: "muscle", p: "명", m: "근육", f: ["muscle", "muscles"], lv: 2 },
  { w: "museum", p: "명", m: "박물관, 미술관", f: ["museum"], lv: 1 },
  { w: "music", p: "명", m: "음악", f: ["music"], lv: 1 },
  { w: "musical", p: "명", m: "뮤지컬, 음악의", f: ["musical", "musicals"], lv: 2 },
  { w: "myth", p: "명", m: "신화, 근거 없는 믿음", f: ["myths"], lv: 3 },
  { w: "name", p: "명", m: "이름, 이름을 짓다", f: ["name"], lv: 1 },
  { w: "narrow", p: "형", m: "좁은", f: ["narrow"], lv: 2 },
  { w: "nation", p: "명", m: "국가, 국민", f: ["nation"], lv: 2 },
  { w: "national", p: "형", m: "국가의, 국립의", f: ["national"], lv: 2 },
  { w: "native", p: "형", m: "원어민의, 토박이의", f: ["native"], lv: 2 },
  { w: "natural", p: "형", m: "자연의, 자연스러운", f: ["natural"], lv: 2 },
  { w: "nature", p: "명", m: "자연, 본성", f: ["nature"], lv: 1 },
  { w: "near", p: "전", m: "~ 가까이에, 가까운", f: ["near"], lv: 1 },
  { w: "necessary", p: "형", m: "필요한", f: ["necessary"], lv: 2 },
  { w: "neck", p: "명", m: "목", f: ["neck"], lv: 1 },
  { w: "need", p: "동", m: "필요하다, 필요", f: ["need", "needed", "needs"], lv: 1 },
  { w: "needlework", p: "명", m: "바느질, 자수", f: ["needlework"], lv: 3 },
  { w: "negative", p: "형", m: "부정적인, 나쁜", f: ["negative"], lv: 2 },
  { w: "negotiate", p: "동", m: "협상하다", f: ["negotiate"], lv: 3 },
  { w: "neighbor", p: "명", m: "이웃, 이웃 사람", f: ["neighbor", "neighbors"], lv: 1 },
  { w: "neighboring", p: "형", m: "이웃의, 인접한", f: ["neighboring"], lv: 2 },
  { w: "nervous", p: "형", m: "긴장한, 불안한", f: ["nervous"], lv: 2 },
  { w: "net", p: "명", m: "그물, 네트", f: ["net"], lv: 2 },
  { w: "networking", p: "명", m: "관계망 형성, 네트워킹", f: ["networking"], lv: 3 },
  { w: "never", p: "부", m: "결코 ~않다, 한 번도 ~않다", f: ["never"], lv: 1 },
  { w: "nevertheless", p: "부", m: "그럼에도 불구하고", f: ["nevertheless"], lv: 3 },
  { w: "new", p: "형", m: "새로운", f: ["new"], lv: 1 },
  { w: "news", p: "명", m: "소식, 뉴스", f: ["news"], lv: 1 },
  { w: "newspaper", p: "명", m: "신문", f: ["newspaper", "newspapers"], lv: 1 },
  { w: "next", p: "형", m: "다음의, 옆의", f: ["next"], lv: 1 },
  { w: "nice", p: "형", m: "좋은, 친절한", f: ["nice", "nicest"], lv: 1 },
  { w: "night", p: "명", m: "밤", f: ["night", "nights"], lv: 1 },
  { w: "nine", p: "명", m: "아홉, 9", f: ["nine"], lv: 1 },
  { w: "noise", p: "명", m: "소음, 소리", f: ["noise"], lv: 1 },
  { w: "noisy", p: "형", m: "시끄러운", f: ["noisy"], lv: 1 },
  { w: "none", p: "대", m: "아무도 ~않다, 하나도 ~않다", f: ["none"], lv: 2 },
  { w: "noodle", p: "명", m: "국수, 면", f: ["noodles"], lv: 1 },
  { w: "noon", p: "명", m: "정오, 낮 12시", f: ["noon"], lv: 1 },
  { w: "normal", p: "형", m: "보통의, 정상적인", f: ["normal"], lv: 2 },
  { w: "north", p: "명", m: "북쪽", f: ["north"], lv: 1 },
  { w: "nose", p: "명", m: "코", f: ["nose"], lv: 1 },
  { w: "note", p: "명", m: "참고, 메모, 주의", f: ["note"], lv: 1 },
  { w: "notebook", p: "명", m: "공책", f: ["notebook"], lv: 1 },
  { w: "nothing", p: "대", m: "아무것도 ~않다", f: ["nothing"], lv: 1 },
  { w: "noticeable", p: "형", m: "눈에 띄는, 뚜렷한", f: ["noticeable"], lv: 3 },
  { w: "notice", p: "동", m: "알아차리다, 공지", f: ["noticed"], lv: 2 },
  { w: "novel", p: "명", m: "소설", f: ["novel"], lv: 2 },
  { w: "November", p: "명", m: "11월", f: ["november"], lv: 1 },
  { w: "now", p: "부", m: "지금, 이제", f: ["now"], lv: 1 },
  { w: "nowadays", p: "부", m: "요즘에는", f: ["nowadays"], lv: 2 },
  { w: "number", p: "명", m: "수, 숫자, 번호", f: ["number"], lv: 1 },
  { w: "nurse", p: "명", m: "간호사", f: ["nurse"], lv: 1 },
  { w: "object", p: "명", m: "물체, 물건, 목적", f: ["object", "objects"], lv: 2 },
  { w: "observe", p: "동", m: "관찰하다, 준수하다", f: ["observe"], lv: 2 },
  { w: "obvious", p: "형", m: "분명한, 명백한", f: ["obvious"], lv: 2 },
  { w: "occasion", p: "명", m: "경우, 때, 행사", f: ["occasions"], lv: 2 },
  { w: "ocean", p: "명", m: "바다, 대양", f: ["ocean"], lv: 1 },
  { w: "off", p: "부", m: "떨어져, 꺼져, 쉬는", f: ["off"], lv: 1 },
  { w: "offer", p: "동", m: "제공하다, 제안하다", f: ["offer", "offered"], lv: 2 },
  { w: "office", p: "명", m: "사무실, 회사", f: ["office"], lv: 1 },
  { w: "often", p: "부", m: "자주, 종종", f: ["often"], lv: 1 },
  { w: "oil", p: "명", m: "기름, 석유", f: ["oil"], lv: 1 },
  { w: "old", p: "형", m: "늙은, 오래된, ~살의", f: ["old", "oldest"], lv: 1 },
  { w: "once", p: "부", m: "한 번, 한때, ~하자마자", f: ["once"], lv: 1 },
  { w: "ondol", p: "명", m: "온돌", f: ["ondol"], lv: 2 },
  { w: "oneself", p: "대", m: "자기 자신", f: ["oneself"], lv: 2 },
  { w: "onion", p: "명", m: "양파", f: ["onion"], lv: 1 },
  { w: "online", p: "형", m: "온라인의, 온라인으로", f: ["online"], lv: 1 },
  { w: "open", p: "동", m: "열다, 열려 있는", f: ["open", "opened", "opens"], lv: 1 },
  { w: "opening", p: "명", m: "개장, 운영(시간), 개막", f: ["opening"], lv: 2 },
  { w: "operate", p: "동", m: "운영하다, 작동하다", f: ["operating"], lv: 2 },
  { w: "operation", p: "명", m: "운영, 작동, 수술", f: ["operations"], lv: 2 },
  { w: "opinion", p: "명", m: "의견", f: ["opinion"], lv: 2 },
  { w: "opportunity", p: "명", m: "기회", f: ["opportunity"], lv: 2, u: true },
  { w: "order", p: "명", m: "주문(하다), 순서, 명령", f: ["order", "ordered", "orders"], lv: 1 },
  { w: "ordinary", p: "형", m: "평범한, 보통의", f: ["ordinary"], lv: 2 },
  { w: "organic", p: "형", m: "유기농의", f: ["organic"], lv: 2 },
  { w: "origin", p: "명", m: "기원, 유래", f: ["origin", "origins"], lv: 2 },
  { w: "original", p: "형", m: "원래의, 독창적인", f: ["original"], lv: 2 },
  { w: "other", p: "대", m: "다른 사람들, 다른 것", f: ["others"], lv: 1 },
  { w: "out", p: "부", m: "밖으로, 밖에", f: ["out"], lv: 1 },
  { w: "outer", p: "형", m: "바깥의, 외부의", f: ["outer"], lv: 2 },
  { w: "outside", p: "부", m: "밖에, 밖으로, 바깥", f: ["outside"], lv: 1 },
  { w: "oven", p: "명", m: "오븐", f: ["oven"], lv: 1 },
  { w: "overall", p: "형", m: "전반적인, 종합적인", f: ["overall"], lv: 2 },
  { w: "overcome", p: "동", m: "극복하다", f: ["overcome"], lv: 2 },
  { w: "oversized", p: "형", m: "너무 큰, 특대의", f: ["oversized"], lv: 3 },
  { w: "overuse", p: "명", m: "과다 사용, 남용", f: ["overuse"], lv: 3 },
  { w: "owner", p: "명", m: "주인, 소유자", f: ["owners"], lv: 2 },
  { w: "oxygen", p: "명", m: "산소", f: ["oxygen"], lv: 2 },
  { w: "ozone", p: "명", m: "오존", f: ["ozone"], lv: 3 },
  { w: "package", p: "명", m: "소포, 꾸러미", f: ["package"], lv: 2 },
  { w: "pain", p: "명", m: "고통, 통증", f: ["pain"], lv: 1 },
  { w: "painful", p: "형", m: "고통스러운, 아픈", f: ["painful"], lv: 2 },
  { w: "painless", p: "형", m: "고통 없는", f: ["painless"], lv: 3 },
  { w: "paint", p: "동", m: "그리다, 칠하다", f: ["paint", "painted"], lv: 1 },
  { w: "painting", p: "명", m: "그림, 그림 그리기", f: ["painting", "paintings"], lv: 1 },
  { w: "pair", p: "명", m: "쌍, 켤레, 벌", f: ["pair"], lv: 1 },
  { w: "palace", p: "명", m: "궁전, 궁궐", f: ["palace"], lv: 2 },
  { w: "paper", p: "명", m: "종이, 신문, 서류", f: ["paper"], lv: 1 },
  { w: "paradise", p: "명", m: "천국, 낙원", f: ["paradise"], lv: 2 },
  { w: "parent", p: "명", m: "부모", f: ["parent", "parents"], lv: 1 },
  { w: "park", p: "명", m: "공원, 주차하다", f: ["park"], lv: 1 },
  { w: "parking", p: "명", m: "주차", f: ["parking"], lv: 1 },
  { w: "parrot", p: "명", m: "앵무새", f: ["parrot", "parrots"], lv: 2 },
  { w: "part", p: "명", m: "부분, 일부, 역할", f: ["part", "parts"], lv: 1 },
  { w: "participant", p: "명", m: "참가자", f: ["participants"], lv: 3 },
  { w: "participate", p: "동", m: "참여하다, 참가하다", f: ["participate", "participating"], lv: 2 },
  { w: "particular", p: "형", m: "특정한, 특별한", f: ["particular"], lv: 2 },
  { w: "party", p: "명", m: "파티, 모임", f: ["party"], lv: 1 },
  { w: "pass", p: "동", m: "지나가다, 통과하다, 건네다", f: ["pass", "passed", "passing"], lv: 1 },
  { w: "passenger", p: "명", m: "승객", f: ["passengers"], lv: 2 },
  { w: "passport", p: "명", m: "여권", f: ["passport"], lv: 2 },
  { w: "password", p: "명", m: "비밀번호", f: ["password"], lv: 2 },
  { w: "past", p: "명", m: "과거, 지나간", f: ["past"], lv: 1 },
  { w: "pasta", p: "명", m: "파스타", f: ["pasta"], lv: 1 },
  { w: "path", p: "명", m: "길, 경로", f: ["paths"], lv: 2 },
  { w: "patience", p: "명", m: "인내, 참을성", f: ["patience"], lv: 2 },
  { w: "patient", p: "명", m: "환자, 참을성 있는", f: ["patients"], lv: 2 },
  { w: "pattern", p: "명", m: "양식, 패턴, 무늬", f: ["patterns"], lv: 2 },
  { w: "pay", p: "동", m: "지불하다, 돈을 내다", f: ["pay"], lv: 1 },
  { w: "peace", p: "명", m: "평화", f: ["peace"], lv: 1 },
  { w: "pen", p: "명", m: "펜", f: ["pen"], lv: 1 },
  { w: "pencil", p: "명", m: "연필", f: ["pencil"], lv: 1 },
  { w: "people", p: "명", m: "사람들", f: ["people"], lv: 1 },
  { w: "pepper", p: "명", m: "후추, 고추", f: ["pepper"], lv: 2 },
  { w: "per", p: "전", m: "~당, ~마다", f: ["per"], lv: 2 },
  { w: "percent", p: "명", m: "퍼센트", f: ["percent"], lv: 2 },
  { w: "perfect", p: "형", m: "완벽한, 딱 좋은", f: ["perfect"], lv: 1 },
  { w: "perfectly", p: "부", m: "완벽하게", f: ["perfectly"], lv: 2 },
  { w: "perform", p: "동", m: "공연하다, 수행하다", f: ["perform", "performing"], lv: 2 },
  { w: "performance", p: "명", m: "공연, 성과, 수행", f: ["performance", "performances"], lv: 2 },
  { w: "permit", p: "동", m: "허락하다, 허용하다", f: ["permitted"], lv: 2 },
  { w: "person", p: "명", m: "사람", f: ["person"], lv: 1 },
  { w: "personal", p: "형", m: "개인의, 개인적인", f: ["personal"], lv: 2 },
  { w: "personality", p: "명", m: "성격, 개성", f: ["personality"], lv: 2 },
  { w: "pet", p: "명", m: "애완동물", f: ["pet", "pets"], lv: 1 },
  { w: "pharmacy", p: "명", m: "약국", f: ["pharmacy"], lv: 2 },
  { w: "phone", p: "명", m: "전화, 휴대폰", f: ["phone"], lv: 1 },
  { w: "photo", p: "명", m: "사진", f: ["photo"], lv: 1 },
  { w: "photograph", p: "명", m: "사진", f: ["photographs"], lv: 2 },
  { w: "photography", p: "명", m: "사진 촬영, 사진술", f: ["photography"], lv: 2 },
  { w: "physical", p: "형", m: "신체의, 물리적인", f: ["physical"], lv: 2 },
  { w: "piano", p: "명", m: "피아노", f: ["piano"], lv: 1 },
  { w: "pick", p: "동", m: "따다, 고르다, 줍다", f: ["pick", "picking"], lv: 1 },
  { w: "picnic", p: "명", m: "소풍", f: ["picnic"], lv: 1 },
  { w: "picture", p: "명", m: "그림, 사진", f: ["picture", "pictures"], lv: 1 },
  { w: "pillow", p: "명", m: "베개", f: ["pillows"], lv: 2 },
  { w: "pineapple", p: "명", m: "파인애플", f: ["pineapple"], lv: 1 },
  { w: "pizza", p: "명", m: "피자", f: ["pizza"], lv: 1, u: true },
  { w: "place", p: "명", m: "장소, 곳, 놓다", f: ["place", "placed", "places"], lv: 1 },
  { w: "placement", p: "명", m: "배치, 배정", f: ["placement"], lv: 3 },
  { w: "plan", p: "명", m: "계획(하다)", f: ["plan", "planned", "planning", "plans"], lv: 1 },
  { w: "plane", p: "명", m: "비행기", f: ["plane"], lv: 1 },
  { w: "plant", p: "명", m: "식물, 심다", f: ["plant", "plants"], lv: 1 },
  { w: "plastic", p: "명", m: "플라스틱, 플라스틱의", f: ["plastic"], lv: 1 },
  { w: "play", p: "동", m: "놀다, (경기·악기를) 하다", f: ["play", "played", "playing"], lv: 1 },
  { w: "player", p: "명", m: "선수, 연주자", f: ["players"], lv: 1 },
  { w: "playground", p: "명", m: "놀이터, 운동장", f: ["playground"], lv: 1 },
  { w: "pleasant", p: "형", m: "즐거운, 쾌적한", f: ["pleasant"], lv: 2 },
  { w: "please", p: "부", m: "제발, 부디, 기쁘게 하다", f: ["please"], lv: 1 },
  { w: "pleased", p: "형", m: "기쁜, 만족한", f: ["pleased"], lv: 2 },
  { w: "pleasure", p: "명", m: "기쁨, 즐거움", f: ["pleasure"], lv: 2 },
  { w: "plenty", p: "명", m: "많음, 풍부함(plenty of)", f: ["plenty"], lv: 2 },
  { w: "pocket", p: "명", m: "주머니", f: ["pockets"], lv: 1 },
  { w: "point", p: "명", m: "요점, 점수, 가리키다", f: ["point", "pointing", "points"], lv: 1 },
  { w: "poisoning", p: "명", m: "중독", f: ["poisoning"], lv: 3 },
  { w: "policy", p: "명", m: "정책, 방침", f: ["policy", "policies"], lv: 2 },
  { w: "polite", p: "형", m: "예의 바른, 공손한", f: ["polite"], lv: 2, u: true },
  { w: "pollute", p: "동", m: "오염시키다", f: ["pollutes"], lv: 2 },
  { w: "pollution", p: "명", m: "오염, 공해", f: ["pollution"], lv: 2 },
  { w: "pool", p: "명", m: "수영장, 웅덩이", f: ["pool"], lv: 1 },
  { w: "poor", p: "형", m: "가난한, 불쌍한, 서투른", f: ["poor"], lv: 1 },
  { w: "pop", p: "명", m: "대중음악, 팝", f: ["pop"], lv: 1 },
  { w: "popular", p: "형", m: "인기 있는", f: ["popular"], lv: 1 },
  { w: "population", p: "명", m: "인구, 개체 수", f: ["population", "populations"], lv: 2 },
  { w: "position", p: "명", m: "위치, 자리, 직위", f: ["position"], lv: 2 },
  { w: "positive", p: "형", m: "긍정적인, 좋은", f: ["positive"], lv: 2 },
  { w: "possible", p: "형", m: "가능한", f: ["possible"], lv: 1 },
  { w: "post", p: "명", m: "우편, 게시하다", f: ["post"], lv: 2 },
  { w: "out of order", p: "숙어", m: "고장 난", f: ["out of order"], lv: 2, ph: true, u: true },
  { w: "make fun of", p: "숙어", m: "~을 놀리다", f: ["make fun of", "made fun of", "making fun of"], lv: 2, ph: true, u: true },
  { w: "look forward to", p: "숙어", m: "~을 고대하다", f: ["look forward to", "looking forward to"], lv: 2, ph: true, u: true },
  { w: "lose weight", p: "숙어", m: "살을 빼다", f: ["lose weight", "lost weight", "losing weight"], lv: 2, ph: true, u: true },
  { w: "participate in", p: "숙어", m: "~에 참여하다", f: ["participate in", "participated in", "participating in"], lv: 2, ph: true, u: true },
  { w: "No news is good news", p: "속담", m: "무소식이 희소식이다", f: ["no news is good news"], lv: 2, ph: true, u: true },
  { w: "No pain, no gain", p: "속담", m: "고통 없이는 얻는 것도 없다", f: ["no pain, no gain"], lv: 2, ph: true, u: true },
  { w: "Look before you leap", p: "속담", m: "돌다리도 두들겨 보고 건너라", f: ["look before you leap"], lv: 2, ph: true, u: true }
);
