// 영어 기출 단어장 (파트 5)
(window.ENGLISH_VOCAB = window.ENGLISH_VOCAB || []).push(
  { w: "potato", p: "명", m: "감자", f: ["potato"], lv: 1 },
  { w: "powder", p: "명", m: "가루, 분말", f: ["powder", "powders"], lv: 2 },
  { w: "power", p: "명", m: "힘, 능력, 전력", f: ["power"], lv: 1 },
  { w: "practice", p: "동", m: "연습하다, 실천하다", f: ["practice", "practicing"], lv: 1 },
  { w: "predict", p: "동", m: "예측하다", f: ["predict"], lv: 2 },
  { w: "prefer", p: "동", m: "~을 더 좋아하다", f: ["prefer"], lv: 2 },
  { w: "prepare", p: "동", m: "준비하다", f: ["prepare"], lv: 1 },
  { w: "present", p: "명", m: "선물, 현재", f: ["present"], lv: 1 },
  { w: "presentation", p: "명", m: "발표, 프레젠테이션", f: ["presentation", "presentations"], lv: 2 },
  { w: "preserve", p: "동", m: "보존하다, 지키다", f: ["preserve"], lv: 3 },
  { w: "pressure", p: "명", m: "압박, 압력", f: ["pressure"], lv: 2 },
  { w: "pretty", p: "부", m: "꽤, 상당히, 예쁜", f: ["pretty"], lv: 1 },
  { w: "prevent", p: "동", m: "막다, 예방하다", f: ["prevent", "prevented"], lv: 2 },
  { w: "prevention", p: "명", m: "예방, 방지", f: ["prevention"], lv: 3 },
  { w: "price", p: "명", m: "가격", f: ["price", "prices"], lv: 1 },
  { w: "print", p: "동", m: "인쇄하다, 출력하다", f: ["print"], lv: 1 },
  { w: "printer", p: "명", m: "프린터, 인쇄기", f: ["printer"], lv: 1 },
  { w: "prize", p: "명", m: "상, 상품", f: ["prize"], lv: 1 },
  { w: "problem", p: "명", m: "문제", f: ["problem", "problems"], lv: 1 },
  { w: "process", p: "명", m: "과정, 절차", f: ["process"], lv: 2 },
  { w: "produce", p: "동", m: "생산하다, 만들어 내다", f: ["produce"], lv: 2 },
  { w: "product", p: "명", m: "제품, 상품", f: ["product", "products"], lv: 2 },
  { w: "production", p: "명", m: "생산, 제작", f: ["production"], lv: 2 },
  { w: "productive", p: "형", m: "생산적인", f: ["productive"], lv: 3 },
  { w: "professional", p: "형", m: "전문적인, 직업의", f: ["professional"], lv: 2 },
  { w: "professor", p: "명", m: "교수", f: ["professor"], lv: 2 },
  { w: "program", p: "명", m: "프로그램", f: ["program", "programs"], lv: 1 },
  { w: "project", p: "명", m: "과제, 프로젝트", f: ["project"], lv: 2 },
  { w: "promise", p: "명", m: "약속, 약속하다", f: ["promise"], lv: 1 },
  { w: "promising", p: "형", m: "유망한, 장래성 있는", f: ["promising"], lv: 3 },
  { w: "promote", p: "동", m: "촉진하다, 홍보하다", f: ["promotes"], lv: 3 },
  { w: "proper", p: "형", m: "적절한, 올바른", f: ["proper"], lv: 2 },
  { w: "properly", p: "부", m: "제대로, 적절하게", f: ["properly"], lv: 2 },
  { w: "protect", p: "동", m: "보호하다", f: ["protect", "protecting"], lv: 2 },
  { w: "protein", p: "명", m: "단백질", f: ["protein"], lv: 2 },
  { w: "proud", p: "형", m: "자랑스러운", f: ["proud"], lv: 1 },
  { w: "prove", p: "동", m: "증명하다", f: ["prove"], lv: 2 },
  { w: "proverb", p: "명", m: "속담", f: ["proverbs"], lv: 2 },
  { w: "provide", p: "동", m: "제공하다", f: ["provide", "provided", "provides"], lv: 2 },
  { w: "psychologist", p: "명", m: "심리학자", f: ["psychologists"], lv: 3 },
  { w: "public", p: "형", m: "공공의, 대중의", f: ["public"], lv: 2 },
  { w: "punish", p: "동", m: "처벌하다, 벌주다", f: ["punish"], lv: 2 },
  { w: "purchase", p: "동", m: "구매하다, 구입", f: ["purchase", "purchased"], lv: 2 },
  { w: "purpose", p: "명", m: "목적", f: ["purpose", "purposes"], lv: 2 },
  { w: "put", p: "동", m: "놓다, 두다", f: ["put"], lv: 1 },
  { w: "put on", p: "숙어", m: "~을 입다, 착용하다", f: ["put on"], lv: 1, ph: true, u: true },
  { w: "put off", p: "숙어", m: "미루다, 연기하다", f: ["put off"], lv: 2, ph: true, u: true },
  { w: "quality", p: "명", m: "질, 품질", f: ["quality"], lv: 2 },
  { w: "question", p: "명", m: "질문, 문제", f: ["question", "questions"], lv: 1 },
  { w: "quick", p: "형", m: "빠른", f: ["quick"], lv: 1 },
  { w: "quickly", p: "부", m: "빨리, 빠르게", f: ["quickly"], lv: 1 },
  { w: "quiet", p: "형", m: "조용한", f: ["quiet"], lv: 1 },
  { w: "quit", p: "동", m: "그만두다, 끊다", f: ["quit"], lv: 2 },
  { w: "quite", p: "부", m: "꽤, 상당히", f: ["quite"], lv: 1 },
  { w: "quiz", p: "명", m: "퀴즈, 간단한 시험", f: ["quiz"], lv: 1 },
  { w: "rabbit", p: "명", m: "토끼", f: ["rabbits"], lv: 1 },
  { w: "race", p: "명", m: "경주, 달리기 시합", f: ["race"], lv: 1 },
  { w: "racket", p: "명", m: "라켓", f: ["racket"], lv: 1 },
  { w: "radiation", p: "명", m: "방사선, 복사", f: ["radiation"], lv: 3 },
  { w: "rain", p: "동", m: "비가 오다, 비", f: ["rain", "rained", "raining", "rains"], lv: 1 },
  { w: "raise", p: "동", m: "올리다, 기르다, 모금하다", f: ["raise"], lv: 2 },
  { w: "random", p: "형", m: "무작위의, 임의의", f: ["random"], lv: 3 },
  { w: "rapid", p: "형", m: "빠른, 급속한", f: ["rapid"], lv: 2 },
  { w: "rapidly", p: "부", m: "빠르게, 급속히", f: ["rapidly"], lv: 2 },
  { w: "rare", p: "형", m: "드문, 희귀한", f: ["rare"], lv: 2 },
  { w: "rate", p: "명", m: "비율, 속도, 요금", f: ["rates"], lv: 2 },
  { w: "rather", p: "부", m: "오히려, 다소", f: ["rather"], lv: 2 },
  { w: "reach", p: "동", m: "~에 이르다, 도달하다", f: ["reach"], lv: 2 },
  { w: "react", p: "동", m: "반응하다", f: ["reacting"], lv: 2 },
  { w: "read", p: "동", m: "읽다", f: ["read", "reading"], lv: 1 },
  { w: "reader", p: "명", m: "독자, 읽는 사람", f: ["reader"], lv: 1 },
  { w: "ready", p: "형", m: "준비된", f: ["ready"], lv: 1 },
  { w: "real", p: "형", m: "진짜의, 실제의", f: ["real"], lv: 1 },
  { w: "realize", p: "동", m: "깨닫다, 알아차리다", f: ["realized"], lv: 2 },
  { w: "really", p: "부", m: "정말, 진짜로", f: ["really"], lv: 1 },
  { w: "reason", p: "명", m: "이유", f: ["reason", "reasons"], lv: 1 },
  { w: "receive", p: "동", m: "받다", f: ["receive", "receiving"], lv: 2 },
  { w: "recent", p: "형", m: "최근의", f: ["recent"], lv: 2 },
  { w: "recently", p: "부", m: "최근에", f: ["recently"], lv: 2 },
  { w: "recipe", p: "명", m: "조리법, 요리법", f: ["recipes"], lv: 2 },
  { w: "recommend", p: "동", m: "추천하다, 권하다", f: ["recommend", "recommended"], lv: 2 },
  { w: "recommendation", p: "명", m: "추천, 권고", f: ["recommendation"], lv: 3 },
  { w: "record", p: "명", m: "기록, 기록하다", f: ["record"], lv: 2 },
  { w: "recover", p: "동", m: "회복하다", f: ["recover"], lv: 2 },
  { w: "recycle", p: "동", m: "재활용하다", f: ["recycle", "recycled", "recycling"], lv: 2 },
  { w: "red", p: "형", m: "빨간", f: ["red"], lv: 1 },
  { w: "reduce", p: "동", m: "줄이다, 감소시키다", f: ["reduce", "reduces", "reducing"], lv: 2 },
  { w: "refer", p: "동", m: "(~라고) 부르다, 언급하다", f: ["referred"], lv: 3 },
  { w: "refund", p: "명", m: "환불, 환불하다", f: ["refund", "refunds"], lv: 2 },
  { w: "region", p: "명", m: "지역", f: ["region"], lv: 2 },
  { w: "register", p: "동", m: "등록하다", f: ["register"], lv: 2 },
  { w: "regret", p: "동", m: "후회하다", f: ["regret", "regretted"], lv: 2 },
  { w: "regular", p: "형", m: "규칙적인, 정기적인", f: ["regular"], lv: 2 },
  { w: "regularly", p: "부", m: "규칙적으로, 정기적으로", f: ["regularly"], lv: 2 },
  { w: "relate", p: "동", m: "관련시키다, 관련되다", f: ["relate", "related"], lv: 2 },
  { w: "relationship", p: "명", m: "관계", f: ["relationship", "relationships"], lv: 2 },
  { w: "relax", p: "동", m: "휴식을 취하다, 긴장을 풀다", f: ["relax"], lv: 1 },
  { w: "relieve", p: "동", m: "덜어 주다, 완화하다", f: ["relieve"], lv: 3 },
  { w: "rely", p: "동", m: "의지하다, 의존하다", f: ["rely"], lv: 2 },
  { w: "remain", p: "동", m: "남다, 여전히 ~이다", f: ["remain", "remained", "remains"], lv: 2 },
  { w: "remember", p: "동", m: "기억하다", f: ["remember", "remembering"], lv: 1 },
  { w: "remind", p: "동", m: "상기시키다", f: ["remind"], lv: 2 },
  { w: "remove", p: "동", m: "제거하다, 없애다", f: ["remove", "removing"], lv: 2 },
  { w: "rent", p: "동", m: "빌리다, 임대하다", f: ["rent"], lv: 2 },
  { w: "repair", p: "동", m: "수리하다, 수리", f: ["repairing", "repairs"], lv: 2 },
  { w: "repeat", p: "동", m: "반복하다", f: ["repeat", "repeating"], lv: 2 },
  { w: "replace", p: "동", m: "대체하다, 교체하다", f: ["replaced"], lv: 2 },
  { w: "reply", p: "명", m: "답장, 대답하다", f: ["reply"], lv: 2 },
  { w: "report", p: "명", m: "보고서, 보고하다", f: ["report", "reported"], lv: 2 },
  { w: "reporter", p: "명", m: "기자", f: ["reporter", "reporters"], lv: 1 },
  { w: "require", p: "동", m: "요구하다, 필요로 하다", f: ["required", "requires"], lv: 2 },
  { w: "research", p: "명", m: "연구, 조사", f: ["research"], lv: 2 },
  { w: "reservation", p: "명", m: "예약", f: ["reservation", "reservations"], lv: 2, u: true },
  { w: "reserve", p: "동", m: "예약하다", f: ["reserve", "reserved"], lv: 2 },
  { w: "resort", p: "명", m: "리조트, 휴양지", f: ["resort"], lv: 2 },
  { w: "respect", p: "동", m: "존중하다, 존경하다", f: ["respect"], lv: 2 },
  { w: "respond", p: "동", m: "응답하다, 반응하다", f: ["respond"], lv: 2 },
  { w: "response", p: "명", m: "응답, 반응", f: ["response"], lv: 2 },
  { w: "responsibility", p: "명", m: "책임", f: ["responsibility"], lv: 3 },
  { w: "rest", p: "명", m: "휴식, 나머지", f: ["rest"], lv: 1 },
  { w: "restaurant", p: "명", m: "식당", f: ["restaurant", "restaurants"], lv: 1 },
  { w: "result", p: "명", m: "결과, (결과로) 생기다", f: ["result", "resulting", "results"], lv: 2 },
  { w: "return", p: "동", m: "돌아오다, 반납하다", f: ["return"], lv: 1 },
  { w: "reusable", p: "형", m: "재사용할 수 있는", f: ["reusable"], lv: 3 },
  { w: "reuse", p: "동", m: "재사용하다", f: ["reusing"], lv: 2 },
  { w: "review", p: "명", m: "후기, 복습, 검토", f: ["review", "reviews"], lv: 2 },
  { w: "reward", p: "명", m: "보상, 보상하다", f: ["rewards"], lv: 2 },
  { w: "rice", p: "명", m: "쌀, 밥", f: ["rice"], lv: 1 },
  { w: "rich", p: "형", m: "부유한, 풍부한", f: ["rich"], lv: 1 },
  { w: "rid", p: "동", m: "없애다(get rid of)", f: ["rid"], lv: 2 },
  { w: "ride", p: "동", m: "타다", f: ["ride", "riding"], lv: 1 },
  { w: "right", p: "형", m: "옳은, 맞는, 오른쪽의", f: ["right"], lv: 1 },
  { w: "rise", p: "동", m: "오르다, 상승하다", f: ["rise", "rising"], lv: 2 },
  { w: "risk", p: "명", m: "위험", f: ["risks"], lv: 2 },
  { w: "river", p: "명", m: "강", f: ["river"], lv: 1 },
  { w: "road", p: "명", m: "길, 도로", f: ["road"], lv: 1 },
  { w: "robot", p: "명", m: "로봇", f: ["robots"], lv: 1 },
  { w: "rock", p: "명", m: "바위, 암석", f: ["rock", "rocks"], lv: 1 },
  { w: "romantic", p: "형", m: "낭만적인", f: ["romantic"], lv: 2 },
  { w: "room", p: "명", m: "방", f: ["room", "rooms"], lv: 1 },
  { w: "root", p: "명", m: "뿌리", f: ["roots"], lv: 2 },
  { w: "rose", p: "명", m: "장미", f: ["rose", "roses"], lv: 1, u: true },
  { w: "round", p: "형", m: "둥근", f: ["round"], lv: 1 },
  { w: "rude", p: "형", m: "무례한", f: ["rude"], lv: 2, u: true },
  { w: "rule", p: "명", m: "규칙", f: ["rules"], lv: 1 },
  { w: "run", p: "동", m: "달리다, 운영하다", f: ["run", "running", "runs"], lv: 1 },
  { w: "runner", p: "명", m: "달리는 사람, 주자", f: ["runners"], lv: 1 },
  { w: "runny", p: "형", m: "콧물이 흐르는", f: ["runny"], lv: 3 },
  { w: "rush", p: "동", m: "서두르다, 급히 하다", f: ["rush"], lv: 2 },
  { w: "sad", p: "형", m: "슬픈", f: ["sad"], lv: 1, u: true },
  { w: "sadness", p: "명", m: "슬픔", f: ["sadness"], lv: 2 },
  { w: "safe", p: "형", m: "안전한", f: ["safe"], lv: 1 },
  { w: "safety", p: "명", m: "안전", f: ["safety"], lv: 2 },
  { w: "say", p: "동", m: "말하다", f: ["said", "say", "saying", "says"], lv: 1 },
  { w: "salad", p: "명", m: "샐러드", f: ["salad"], lv: 1 },
  { w: "sale", p: "명", m: "할인 판매, 판매", f: ["sale", "sales"], lv: 1 },
  { w: "salt", p: "명", m: "소금", f: ["salt"], lv: 1 },
  { w: "sand", p: "명", m: "모래", f: ["sand"], lv: 1 },
  { w: "sandwich", p: "명", m: "샌드위치", f: ["sandwich"], lv: 1 },
  { w: "satellite", p: "명", m: "인공위성, 위성", f: ["satellites"], lv: 3 },
  { w: "satisfaction", p: "명", m: "만족", f: ["satisfaction"], lv: 3 },
  { w: "satisfied", p: "형", m: "만족한", f: ["satisfied"], lv: 2 },
  { w: "Saturday", p: "명", m: "토요일", f: ["saturday", "saturdays"], lv: 1 },
  { w: "sauce", p: "명", m: "소스", f: ["sauce"], lv: 1 },
  { w: "save", p: "동", m: "절약하다, 구하다, 저장하다", f: ["save", "saves"], lv: 1 },
  { w: "see", p: "동", m: "보다, 알다", f: ["saw", "see", "seeing"], lv: 1 },
  { w: "scene", p: "명", m: "장면, 현장", f: ["scene"], lv: 2 },
  { w: "schedule", p: "명", m: "일정, 시간표", f: ["schedule", "schedules"], lv: 2 },
  { w: "school", p: "명", m: "학교", f: ["school"], lv: 1 },
  { w: "science", p: "명", m: "과학", f: ["science"], lv: 1 },
  { w: "scientific", p: "형", m: "과학적인", f: ["scientific"], lv: 2 },
  { w: "scientist", p: "명", m: "과학자", f: ["scientists"], lv: 1 },
  { w: "scratch", p: "명", m: "긁힌 자국, 흠집", f: ["scratches"], lv: 3 },
  { w: "screen", p: "명", m: "화면", f: ["screens"], lv: 1 },
  { w: "script", p: "명", m: "대본, 원고", f: ["script"], lv: 3 },
  { w: "sea", p: "명", m: "바다", f: ["sea"], lv: 1 },
  { w: "seafood", p: "명", m: "해산물", f: ["seafood"], lv: 1 },
  { w: "season", p: "명", m: "계절, 철", f: ["season"], lv: 1, u: true },
  { w: "seat", p: "명", m: "좌석, 자리", f: ["seat", "seats"], lv: 1 },
  { w: "seatbelt", p: "명", m: "안전벨트", f: ["seatbelt"], lv: 2 },
  { w: "second", p: "형", m: "두 번째의, 초", f: ["second"], lv: 1 },
  { w: "secondly", p: "부", m: "둘째로", f: ["secondly"], lv: 2 },
  { w: "secret", p: "명", m: "비밀, 비결", f: ["secret"], lv: 1 },
  { w: "seem", p: "동", m: "~인 것 같다", f: ["seem", "seems"], lv: 2 },
  { w: "self", p: "명", m: "자기, 자신(self-)", f: ["self"], lv: 2 },
  { w: "selfish", p: "형", m: "이기적인", f: ["selfish"], lv: 2 },
  { w: "sell", p: "동", m: "팔다", f: ["sell"], lv: 1 },
  { w: "semester", p: "명", m: "학기", f: ["semester"], lv: 2 },
  { w: "send", p: "동", m: "보내다", f: ["send", "sent"], lv: 1 },
  { w: "sense", p: "명", m: "감각, 느낌, 의미", f: ["sense"], lv: 2 },
  { w: "September", p: "명", m: "9월", f: ["september"], lv: 1 },
  { w: "serious", p: "형", m: "심각한, 진지한", f: ["serious"], lv: 2 },
  { w: "seriously", p: "부", m: "심각하게, 진지하게", f: ["seriously"], lv: 2 },
  { w: "serve", p: "동", m: "(음식을) 제공하다, 봉사하다", f: ["serve", "served"], lv: 2 },
  { w: "service", p: "명", m: "서비스, 봉사", f: ["service", "services"], lv: 1 },
  { w: "set", p: "동", m: "놓다, 정하다, 세트", f: ["set"], lv: 1 },
  { w: "seven", p: "명", m: "일곱, 7", f: ["seven"], lv: 1 },
  { w: "several", p: "형", m: "몇몇의, 여러", f: ["several"], lv: 1 },
  { w: "severe", p: "형", m: "심한, 극심한", f: ["severe"], lv: 3 },
  { w: "severely", p: "부", m: "심하게", f: ["severely"], lv: 3 },
  { w: "shake", p: "동", m: "흔들다, 떨다", f: ["shaking"], lv: 2 },
  { w: "shampoo", p: "명", m: "샴푸", f: ["shampoo"], lv: 1 },
  { w: "shape", p: "명", m: "모양, 형태", f: ["shape"], lv: 1 },
  { w: "share", p: "동", m: "공유하다, 나누다", f: ["share"], lv: 1 },
  { w: "shark", p: "명", m: "상어", f: ["sharks"], lv: 1 },
  { w: "sharp", p: "형", m: "날카로운, 뾰족한", f: ["sharp"], lv: 2 },
  { w: "shirt", p: "명", m: "셔츠", f: ["shirt", "shirts"], lv: 1 },
  { w: "shock", p: "명", m: "충격", f: ["shocks"], lv: 2 },
  { w: "shoe", p: "명", m: "신발", f: ["shoes"], lv: 1 },
  { w: "shop", p: "명", m: "가게, 쇼핑하다", f: ["shop"], lv: 1 },
  { w: "shopping", p: "명", m: "쇼핑, 장보기", f: ["shopping"], lv: 1 },
  { w: "short", p: "형", m: "짧은, 키가 작은", f: ["short", "shorter"], lv: 1 },
  { w: "shortage", p: "명", m: "부족", f: ["shortage"], lv: 3 },
  { w: "shoulder", p: "명", m: "어깨", f: ["shoulder"], lv: 1 },
  { w: "show", p: "동", m: "보여 주다, 공연", f: ["show", "showed", "shown", "shows"], lv: 1 },
  { w: "shower", p: "명", m: "샤워", f: ["shower"], lv: 1 },
  { w: "shrink", p: "동", m: "줄어들다", f: ["shrink"], lv: 3 },
  { w: "shut", p: "동", m: "닫다, 끄다(shut down/off)", f: ["shut"], lv: 2 },
  { w: "shy", p: "형", m: "수줍어하는", f: ["shy"], lv: 1 },
  { w: "sick", p: "형", m: "아픈", f: ["sick"], lv: 1 },
  { w: "side", p: "명", m: "옆, 측면, 쪽", f: ["side", "sides"], lv: 1 },
  { w: "sign", p: "동", m: "서명하다, 표지판", f: ["sign", "signed"], lv: 1 },
  { w: "signature", p: "명", m: "서명", f: ["signature"], lv: 2 },
  { w: "silent", p: "형", m: "조용한, 말 없는", f: ["silent"], lv: 2 },
  { w: "similar", p: "형", m: "비슷한", f: ["similar"], lv: 2 },
  { w: "similarity", p: "명", m: "유사점, 닮은 점", f: ["similarities"], lv: 3 },
  { w: "similarly", p: "부", m: "비슷하게, 마찬가지로", f: ["similarly"], lv: 2 },
  { w: "simple", p: "형", m: "간단한, 단순한", f: ["simple"], lv: 1 },
  { w: "simply", p: "부", m: "단순히, 그저", f: ["simply"], lv: 2 },
  { w: "sincerely", p: "부", m: "진심으로(편지 맺음말)", f: ["sincerely"], lv: 2 },
  { w: "singer", p: "명", m: "가수", f: ["singer", "singers"], lv: 1 },
  { w: "single", p: "형", m: "단 하나의, 1인용의", f: ["single"], lv: 2 },
  { w: "sir", p: "명", m: "(남성 존칭) 손님, 선생님", f: ["sir"], lv: 1 },
  { w: "sister", p: "명", m: "여자 형제, 언니, 누나", f: ["sister"], lv: 1 },
  { w: "sit", p: "동", m: "앉다", f: ["sit"], lv: 1 },
  { w: "situation", p: "명", m: "상황", f: ["situation", "situations"], lv: 2 },
  { w: "six", p: "명", m: "여섯, 6", f: ["six"], lv: 1 },
  { w: "sixth", p: "형", m: "여섯 번째의", f: ["sixth"], lv: 1 },
  { w: "size", p: "명", m: "크기, 치수", f: ["size", "sizes"], lv: 1 },
  { w: "sized", p: "형", m: "~크기의(medium-sized)", f: ["sized"], lv: 2 },
  { w: "skate", p: "동", m: "스케이트를 타다", f: ["skate", "skating"], lv: 1 },
  { w: "skiing", p: "명", m: "스키 타기", f: ["skiing"], lv: 1 },
  { w: "skill", p: "명", m: "기술, 능력", f: ["skills"], lv: 2 },
  { w: "skin", p: "명", m: "피부", f: ["skin"], lv: 1 },
  { w: "skip", p: "동", m: "거르다, 건너뛰다", f: ["skip"], lv: 2 },
  { w: "sky", p: "명", m: "하늘", f: ["sky"], lv: 1 },
  { w: "sleep", p: "동", m: "자다, 잠", f: ["sleep", "sleeping"], lv: 1 },
  { w: "sleeplessness", p: "명", m: "불면, 잠 못 이룸", f: ["sleeplessness"], lv: 3 },
  { w: "slice", p: "명", m: "조각, 얇게 썰다", f: ["slice"], lv: 2 },
  { w: "slide", p: "명", m: "미끄럼틀, 미끄러지다", f: ["slides"], lv: 2 },
  { w: "slim", p: "형", m: "날씬한", f: ["slim"], lv: 2 },
  { w: "slow", p: "형", m: "느린", f: ["slow"], lv: 1 },
  { w: "small", p: "형", m: "작은", f: ["small", "smaller"], lv: 1 },
  { w: "smart", p: "형", m: "똑똑한, 영리한", f: ["smart", "smarter"], lv: 1 },
  { w: "smartphone", p: "명", m: "스마트폰", f: ["smartphone", "smartphones"], lv: 1 },
  { w: "smell", p: "명", m: "냄새, 냄새가 나다", f: ["smell", "smelled", "smells"], lv: 1 },
  { w: "smile", p: "동", m: "미소 짓다, 미소", f: ["smile", "smiled", "smiling"], lv: 1 },
  { w: "smoking", p: "명", m: "흡연", f: ["smoking"], lv: 2 },
  { w: "snack", p: "명", m: "간식", f: ["snacks"], lv: 1 },
  { w: "sneakers", p: "명", m: "운동화", f: ["sneakers"], lv: 2 },
  { w: "snow", p: "명", m: "눈, 눈이 오다", f: ["snow"], lv: 1 },
  { w: "so", p: "접", m: "그래서, 그러므로", f: ["so"], lv: 1, u: true },
  { w: "soap", p: "명", m: "비누", f: ["soap"], lv: 1 },
  { w: "soccer", p: "명", m: "축구", f: ["soccer"], lv: 1 },
  { w: "social", p: "형", m: "사회의, 사교적인", f: ["social"], lv: 2 },
  { w: "society", p: "명", m: "사회", f: ["societies", "society"], lv: 2 },
  { w: "sock", p: "명", m: "양말", f: ["socks"], lv: 1 },
  { w: "soda", p: "명", m: "탄산음료", f: ["soda"], lv: 1 },
  { w: "sofa", p: "명", m: "소파", f: ["sofa"], lv: 1 },
  { w: "soft", p: "형", m: "부드러운", f: ["soft"], lv: 1 },
  { w: "software", p: "명", m: "소프트웨어", f: ["software"], lv: 2 },
  { w: "soil", p: "명", m: "흙, 토양", f: ["soil"], lv: 2 },
  { w: "soldier", p: "명", m: "군인", f: ["soldier"], lv: 2 },
  { w: "solution", p: "명", m: "해결책", f: ["solution", "solutions"], lv: 2 },
  { w: "solve", p: "동", m: "해결하다, 풀다", f: ["solve", "solved"], lv: 1 },
  { w: "someday", p: "부", m: "언젠가", f: ["someday"], lv: 1 },
  { w: "someone", p: "대", m: "누군가", f: ["someone"], lv: 1 },
  { w: "something", p: "대", m: "무언가, 어떤 것", f: ["something"], lv: 1 },
  { w: "sometimes", p: "부", m: "가끔, 때때로", f: ["sometimes"], lv: 1 },
  { w: "soon", p: "부", m: "곧", f: ["soon"], lv: 1 },
  { w: "sorry", p: "형", m: "미안한, 유감스러운", f: ["sorry"], lv: 1 },
  { w: "sort", p: "동", m: "분류하다, 정리하다, 종류", f: ["sorts"], lv: 2 },
  { w: "sound", p: "동", m: "~하게 들리다, 소리", f: ["sound", "sounds"], lv: 1 },
  { w: "soup", p: "명", m: "수프, 국", f: ["soup"], lv: 1 },
  { w: "source", p: "명", m: "원천, 근원, 출처", f: ["source", "sources"], lv: 2 },
  { w: "south", p: "명", m: "남쪽", f: ["south"], lv: 1 },
  { w: "southwestern", p: "형", m: "남서부의", f: ["southwestern"], lv: 3 },
  { w: "space", p: "명", m: "공간, 우주", f: ["space", "spaces"], lv: 1 },
  { w: "spaghetti", p: "명", m: "스파게티", f: ["spaghetti"], lv: 1 },
  { w: "speak", p: "동", m: "말하다", f: ["speak", "speaking"], lv: 1 },
  { w: "speaker", p: "명", m: "화자, 연설자, 스피커", f: ["speakers"], lv: 2 },
  { w: "special", p: "형", m: "특별한", f: ["special"], lv: 1 },
  { w: "speech", p: "명", m: "연설, 말", f: ["speech", "speeches"], lv: 2 },
  { w: "speed", p: "명", m: "속도", f: ["speeds"], lv: 1 },
  { w: "spend", p: "동", m: "(시간·돈을) 쓰다, 보내다", f: ["spend", "spending", "spent"], lv: 1 },
  { w: "Rome was not built in a day", p: "속담", m: "로마는 하루아침에 이루어지지 않았다", f: ["rome was not built in a day"], lv: 2, ph: true, u: true },
  { w: "Seeing is believing", p: "속담", m: "백문이 불여일견", f: ["seeing is believing"], lv: 2, ph: true, u: true }
);
